### ISSUE TITLE
Request for new tadoMode

### ISSUE THREAD

**Issue by jeyremy** [nitaybz/homebridge-tado-ac#10]
Hi, 
First of all, Thanks for this plugin, it's awesome.

i was thinking that the two modes for tado "MANUAL" and "TADO_MODE" is a bit restrictive, 
beacause for manual, there is no way to "un-manual" from siri or homekit so you have to launch tado's app. 

For tado_mode (better in my case) it's cool, but again, if you change the temp 5 minutes before changing plan, it's not good for me (or if the next changement is in 8 hours.. )

So, i would love a third mode like with timer (in config.json) like 1,5 hours, is the best. 

Sorry for my bad english.

**Comment by nitaybz** [comment]
If I'll make a mode with timer you'll have to set a permanent time for the mode to be expired... is that sound good? it means that you won't be able to set the time in homekit... only in the config file

**Comment by jeyremy** [comment]
If is just for me, 

Yes ! when i need to get a bit more/less hot in the room, i don't want it for more than 1h30. so it would be awesome !

**Comment by nitaybz** [comment]
ok... I'll make an upgrade to the plugin soon and I'll examine this option

**Comment by nitaybz** [comment]
but I think that this means that every time you send command to your ac it will restart the clock... how does it work in tado app?
once you set up with timer and change settings what happen?

**Comment by jeyremy** [comment]
Hi, 

Yes in the app each command reset the timer. but i think it's ok. 

maybe what is also missing in the plugin is a "return to planning" mode  for when you are in MANUAL mode. 

but that's a goot work.

i'm looking forward to help you, i'm a PHP/Objective-c/Swift dev, and i'm looking for understand Node-js/homebridge

**Comment by nitaybz** [comment]
I didn't really understand what you meant by:
"maybe what is also missing in the plugin is a "return to planning" mode for when you are in MANUAL mode."

and the best practice to start creating stuff with homebridge is to think of what you want to build and duplicate other plugins while changing them to fit your needs... that's what I did... but I had some experience with Javascript.... anyway handling with homebridge made me a node-js expert :)

**Comment by jeyremy** [comment]
I meant that for now we cant cancel a manual consign to the tado within homekit app, 

exemple:
 i change the temp to 28°C, i can't tell "return to planning mode" or "cancel my manual consign"

i have seen in another plugin : 
[/fuzzysb/Tado](https://github.com/fuzzysb/Tado/blob/275098f2a3b545e2a495eb59e0c9c6004682b007/smartapps/fuzzysb/tado-connect.src/tado-connect.groovy)

```
    'deleteEntry': [
        			uri: apiUrl(),
        			path: "/api/v2/homes/" + state.homeId + "/zones/" + args[0] + "/overlay",
        			requestContentType: "application/json",
                    query: [username:settings.username, password:settings.password],
                   	]
```
that is used in method named : endManualControl

But i have for the moment no idea on how to implement it. =D 

My final objective is to let the tado app closed, use only homekit.

**Comment by nitaybz** [comment]
I can add a switch to turn off tado manual control... it’s suppose to be easy...

**Comment by jeyremy** [comment]
thank you very much  !

**Comment by nitaybz** [comment]
check out my last version v2.2

**Comment by jeyremy** [comment]
Thanks a lot, i think i may have not updated correctly because timer and new switch not working in my installation :/

**Comment by nitaybz** [comment]
How did you update?

**Comment by nitaybz** [comment]
Did you see the new readme and updated the config?

**Comment by jeyremy** [comment]
Hi, 

i did a "miss update" with homebridge-tado instead of homebridge-tado-ac 

this being corrected : 
the switch on/off is perfectly working.
the timer for manuals commands seem to be not working here the part of my config : 
`
[...]
        "tadoMode": "TIMER",
        "durationInMinutes": 1 ,
        "maunalControl":true,
        "weatherSensorsEnabled": true,
        "weatherPollingInterval": 10,
        "occupancySensorsEnabled": true,
        "occupancyPollingInterval": 10,
        "anyoneSensor": true
`
Again thanks a lot for your work !

**Comment by nitaybz** [comment]
try to extend duration to more than 1 minute... maybe it's too little for tado
try 90

**Comment by nitaybz** [comment]
@jeyremy I think I know why it's not working, Try to delete the tado related files in the persist folder... I think it should solve the issue

**Comment by nitaybz** [comment]
@jeyremy I noticed there was an error in the code
please try my last version 2.2.10

**Comment by jeyremy** [comment]
i have tested the last version : almost perfect ! thank you !! 

for no reason the "maunalControl":true does not display the button anymore, but the durationInMinutes work perfectly !  

A Big thank you !

**Comment by nitaybz** [comment]
"manualControl": true
works for me... try to restart and if it persist show me your config.

**Comment by nitaybz** [comment]
no reply and all seems to be working...
closing

**Comment by jeyremy** [comment]
Yes ! sorry about that, 
i had miss tipped "manual" ... thanks a lot !
