### ISSUE TITLE
Cooling keeps turning itself off

### ISSUE THREAD

**Issue by ghost** [nitaybz/homebridge-tado-ac#102]
From yesterday, without touching the installation, my Tado system is turning itself off as soon as I turn it on. The "tadoMode" is manual and always has been.

I'm using v4.0.17.

**Comment by nitaybz** [comment]
Please add debug logs and send it over

**Comment by ghost** [comment]
Where are the logs stored?

Best,
Ricky.

**Comment by ghost** [comment]
The weird thing is, when when I use the Tado app to turn it on, this plugin still turns it off. How is that even possible?

Best,
Ricky.

**Comment by nitaybz** [comment]
are you sure it's the plugin? maybe an issue with tado?
try to stop homebridge and see if the issue persist...
you can enable debug logs from the plugin config/settings and see the logs by clicking on the pulse like button in Homebridge UI

**Comment by ghost** [comment]
Sorry, looks like it was something to do with Tado. I think I changed it using the app one day, with a time setting, and maybe that caused it.
