### ISSUE TITLE
How to whitelist/blacklist devices

### ISSUE THREAD

**Issue by bosco90** [nitaybz/homebridge-tado-ac#108]
Hi there,
I have 3 Tado AC devices and only the oldest one is not compatible with HomeKit, so I use this plugin just to integrate it.
Is it possible to expose to HomeKit only that particular device? 

Thanks.

**Comment by nitaybz** [comment]
if you edit the config manually you can remove services for specific device:
https://github.com/nitaybz/homebridge-tado-ac#specific-device-custom-settings

I would just remove all services for all devices you don't want to see

**Comment by bosco90** [comment]
Thanks for the fast answer!

At the moment I've both _disableFan_ and _disableDry_ set to true, tried to add _disabledAcAccessory_ for the 2 devices already compatible but they still there.
I'm not sure about the device/zone ID, where should I find them?

**Comment by bosco90** [comment]
Tried with some device name (the one in HomeKit and the one in Tado app) but without success.

Here is my configuration, I might be blind and not find the issue

        {
            "username": "xxxxx",
            "password": "xxxxx",
            "occupancySensorsEnabled": false,
            "occupancyPollingInterval": 10,
            "anyoneSensor": false,
            "weatherSensorsEnabled": false,
            "weatherPollingInterval": 5,
            "tadoMode": "MANUAL",
            "durationInMinutes": 90,
            "disableFan": true,
            "disableDry": true,
            "disableACAccessory": [
                "Cameretta",
                "Soggiorno"
            ],
            "manualControlSwitch": false,
            "historyStorage": false,
            "extraHumiditySensor": false,
            "forceThermostat": false,
            "forceHeaterCooler": false,
            "statePollingInterval": 30,
            "debug": false,
            "platform": "TadoAC"
        },

**Comment by nitaybz** [comment]
set "debug" to true and try to find the zone ID, use those and see if it helps
