### ISSUE TITLE
No accessory found

### ISSUE THREAD

**Issue by salacika** [nitaybz/homebridge-tado-ac#11]
2.2: This is the first version i installed ever.  Now on weatherSensorsEnabled = true i've got this new fancy stuff Outside Temperature & Solar Intensity Sensors, but nothing else. On weatherSensorsEnabled = false:

![image](https://user-images.githubusercontent.com/10532931/32984693-90811888-ccab-11e7-98e8-703beda335e2.png)

**Comment by nitaybz** [comment]
Do you have Tado smart ac control device? Or other tado device?

**Comment by salacika** [comment]
I have smart ac no other tado device just yet.

**Comment by nitaybz** [comment]
Can you show me more of the logs for when you restart homebridge?

**Comment by salacika** [comment]
![image](https://user-images.githubusercontent.com/10532931/33126154-c1a8d0e2-cf83-11e7-86b5-b423a29b30d4.png)

**Comment by salacika** [comment]
![image](https://user-images.githubusercontent.com/10532931/33126274-358253f8-cf84-11e7-8f2b-f9a498edc2fa.png)

**Comment by salacika** [comment]
any news?

**Comment by nitaybz** [comment]
it's not recognizing your homeID for some reason... can you get your homeID via Old readme?

**Comment by salacika** [comment]
i need to apologize, i made a silly mistake, my password was incorrect. my bad :)
