### ISSUE TITLE
Setting AC Fan to "Auto"

### ISSUE THREAD

**Issue by grork** [nitaybz/homebridge-tado-ac#12]
I had a great install experience, but I'm having one "how to use it" issue:

How do I set a fan to "Auto" after I've set an explicit fan setting? Browsing the code, it seems that there are some places that account for this ("this.steps / max - 1" or similar), but I can't see how this actually gets surfaced in HomeKit (if it does).

Any suggestions or hints?

**Comment by nitaybz** [comment]
hey @grork !

since home app does not have native auto control I could not use it.
so I made the "autoOnly" option, which will set all AC fan speeds to auto mode if possible with all the commands.
all you have to do is set `"autoOnly": true` in your config
