### ISSUE TITLE
TADO_MODE not working

### ISSUE THREAD

**Issue by poliolet** [nitaybz/homebridge-tado-ac#15]
Hi,

I am able to get to work both modes TIMER and MANUAL but when I set it to TADO_MODE it uses MANUAL instead. I have tried every single thing but I can't make it work. Am I missing anything?

`
"platforms": [
     {

       "platform": "TadoAC",
       "name": "Tado AC",
       "username": "****",
       "password": "****",
       "weatherSensorsEnabled": true,
       "weatherPollingInterval": 10,
       "occupancySensorsEnabled": true,
       "occupancyPollingInterval": 5,
       "anyoneSensor": true,
       "tadoMode": "TADO_MODE",
       "autoOnly": true,
       "manualControl": true,
       "extraTemperatureSensor": true
     }
  ]`

**Comment by poliolet** [comment]
Actually I just discovered that the TADO_MODE works when I switch off the AC but it doesn't when I turn it on. Sorry if I am missing anything... but any help is welcome! :)

**Comment by nitaybz** [comment]
Try to delete the tado related files in the persist folder... I think it should solve the issue

**Comment by poliolet** [comment]
Thanks for your quick reply. Unfortunately, the behaviour is the same. :(

**Comment by nitaybz** [comment]
I noticed there was an error in the code
please try my last version 2.2.10

**Comment by poliolet** [comment]
It works now! Thank you :)

**Comment by nitaybz** [comment]
Glad it did the job!
closing...
