### ISSUE TITLE
Problem to change mode

### ISSUE THREAD

**Issue by Francis2b** [nitaybz/homebridge-tado-ac#17]
Hi,

Now that Homebridge is working and homebridge-tado-ac also. I have a small problem.

I can change the temperature in Heating mode but I can't change to COOL or Auto mode in the Home app. 

Let's say that my AC is on Heat @ 30°C, I tap mode-> Cool nothing is happening And the switch go from Heat to Cool to Heat again. Even if in the Terminal windows I can see this:

```
[2017-12-22 13:17:48] [Tado AC] Setting Air Conditioning AC Target Temperature to 30
[2017-12-22 13:18:35] [Tado AC] Setting Air Conditioning AC to COOL
```

When I tap Auto mode there is the same behavior. But this time nothing is displayed in Terminal.
When I tap Off it turns the AC Off. 

Is it due to the fact that my SmartAC is set on Thermostatic Mode and I use a Beta Version of the Tado° app?

**Comment by nitaybz** [comment]
Yes... for some reason it doesn't work well with the thermostat mode... I experienced the same situation...
switch back to normal mode to gain full control over your AC

**Comment by Francis2b** [comment]
OK I asked Tado to switch me back to normal back as soon as they do it I keep you in touch!

**Comment by nitaybz** [comment]
I noticed the error occurred also without thermostatic control...
so I find the issue and solve it... please try my last version 2.2.9

**Comment by Francis2b** [comment]
To update it I just have to type: `sudo npm install -g --unsafe-perm homebridge` ? Will it erase my settings?

**Comment by nitaybz** [comment]
sudo npm install -g homebridge-tado-ac

**Comment by Francis2b** [comment]
I updated it but I still have the same bug. When I enable Cool it enable Heat

**Comment by nitaybz** [comment]
you are right... you need to delete the tado related files in persist folder, there should be one for every zone.
also I noticed another error so please install the latest version before doing this...

let me know how it goes...

**Comment by Francis2b** [comment]
by any chance is there a command that wipes it off?

**Comment by nitaybz** [comment]
depends on your homebridge installation... are there anymore plugins on your homebridge?

**Comment by nitaybz** [comment]
can you give me the location of your config file?

**Comment by Francis2b** [comment]
no just the tado one. The json file? Here is the location: /home/pi/.homebridge/config.json

**Comment by nitaybz** [comment]
so

`rm "/home/pi/.homebridge/persist/yourZoneName Tado"`
replace yourZone name with the name of your tado zone/device

do this for every zone

**Comment by Francis2b** [comment]
And when it's done I reinstall it? Should I rewrite the json file?

**Comment by nitaybz** [comment]
No just install the plugin again and restart homebridge

**Comment by Francis2b** [comment]
Can't remove the file:

pi@raspberrypi:~/.homebridge/accessories $ rm /home/pi/.homebridge/Air Conditioning
rm: cannot remove '/home/pi/.homebridge/Air': No such file or directory
rm: cannot remove 'Conditioning': No such file or directory
pi@raspberrypi:~/.homebridge/accessories $ rm /home/pi/.homebridge/AirConditioning
rm: cannot remove '/home/pi/.homebridge/AirConditioning': No such file or directory
pi@raspberrypi:~/.homebridge/accessories $ 

![img_1566](https://user-images.githubusercontent.com/21141137/34322559-888db006-e82a-11e7-826f-bf0385ecb31a.jpg)

**Comment by nitaybz** [comment]
rm "/home/pi/.homebridge/persist/Air\ Conditioning\ Tado"

**Comment by Francis2b** [comment]
oh ok ! Cool is now working bit Auto still not. The switch goes back to Heat and doesn't want to stay on auto

**Comment by nitaybz** [comment]
Do you have auto mode on your ac? In your tado settings

**Comment by Francis2b** [comment]
Oh I understand why it's because of the thermostatic mode Auto can't be enable! Sorry!

**Comment by nitaybz** [comment]
Exactly... it can only control what you can control through tado app

**Comment by Francis2b** [comment]
Great so this pb is solved! I have another pb with Siri command I'll open a new ticket ;)

**Comment by nitaybz** [comment]
Glad I could help!
