### ISSUE TITLE
Siri won't return the current temperature!

### ISSUE THREAD

**Issue by Francis2b** [nitaybz/homebridge-tado-ac#18]
Hi,

I have some problem with Siri.
When I say "What's the temperature inside?" She answers: "The Air conditining is at 18°C"

She doesn't want to tell me the temperature of the room and the answer is wrong the AC is set to Heating to 25°C

**Comment by Francis2b** [comment]
Strangely if I open the Home app and ask "What's the inside temperature" Siri will give me the right answer! But as soon as I close it she can't answer the question or says : "The Air conditining is at 18°C"

Does this bug come from Apple or Homebridge?

**Comment by nitaybz** [comment]
I'm aware of the issue and I tried to solve it by making an extra temperature sensor, but Siri refuses to use the second temperature sensor and always giving me the minimum ac temperature.
I guess it's an apple bug with the "CoolerHeater" service (Aircon) cause it used to work well when the plugin was thermostat and it was set in the exact same way...

what is also weird is that you can see in the logs while you ask Siri for the temperature, you can see it pull the correct value but Siri is saying something else completely...

I'll leave this issue open so if anyone has any idea on how to solve it, this will be the place...

**Comment by jadomski** [comment]
I’ve been trying to replicate this issue (I have the additional sensor added) and Siri is always telling me the measured temperature. I’m on iOS 11.2.2 - is this issue only affecting certain iOS versions perhaps, or only certain configurations?

**Comment by nitaybz** [comment]
I have the latest iOS (public, no beta), and the issue is solved for me.
the extra sensor added will not be supported soon since it's not brining any value. I tired to overpass the SIri issue (when she is not giving the current temperature) but it didn't work.

Yesterday I asked Siri for the temperature in a room and she gave me the correct value (from the AC).

Let me know if it works for you either...

**Comment by Francis2b** [comment]
You're right if you ask the temperature in a room Siri gives you the correct value. I was using this trick at the beginning. 

Now I have an Elgato Eve Room and... even with that I still need to ask the temperature in a room. In my opinion, the bug is on Siri side

**Comment by jadomski** [comment]
Works fine for me. I have the Elgato Even Room too. I currently have the Tado set to 22ºC. The Tado sensor is reading 25ºC and the Eve Home is reading 30ºC. I have also made sure that my Homebridge is up to date - currently running on version 0.4.36 which is the latest.

I asked Siri "What's the temperature inside?" and received the response "The temperature inside ranges from 25 to 30 degrees Celsius." I have the additional Tado sensor disabled in the and am on iOS 11.2.2 so I can confirm that it is working as expected on my device.

**Comment by nitaybz** [comment]
@Francis2b you have to ask for a temperature in a specific room, that's how it always worked... don't think it's a bug, making sense actually, cause she can't tell you the temperature of the house when she only knows one room...

anyway, seems like it's working as expected... closing the issue
