### ISSUE TITLE
Help on writing a tutorial for the plug-in

### ISSUE THREAD

**Issue by Francis2b** [nitaybz/homebridge-tado-ac#19]
Hi @nitaybz ,

I'm writing a tutorial that I will post on my blog and if you like it you can use it in the README.md.
I was wondering if you'd like to read it to check if I forgot something and if you want me to add something about the fact you helped me make my setup working and thanks to you I was able to write this tutorial to help others?

Let me know how I can contact you for more details if you're interested in ;)

**Comment by nitaybz** [comment]
I’ll be happy to help and get involved... feel free to contact me on nitaybz@gmail.com
Or Skype: nitaybz
