### ISSUE TITLE
Turning on fan stops A/C modes from responding

### ISSUE THREAD

**Issue by jadomski** [nitaybz/homebridge-tado-ac#20]
I've noticed that after using the "Fan" button that my Tado system gets stuck in fan mode and does not apply cooling temperature changes. Here's the a couple sample scenarios I have used to reproduce the issue:

**Fan On -> A/C On**
1. Press the Fan button in the Home app - _Home app shows Fan on and A/C off, Tado app shows unit in Fan mode_
2. Press the A/C button in the Home app - _Home app shows A/C on and Fan off, Tado app shows unit in Fan mode_

**Fan On -> Fan Off -> A/C On**
1. Press the Fan button in the Home app - _Home app shows Fan on and A/C off, Tado app shows unit in Fan mode_
2. Press the Fan button in the Home app - _Home app shows Fan off and A/C off, Tado app shows unit off_
3. Press the A/C button in the Home app - _Home app shows A/C on and Fan off, Tado app shows unit in Fan mode_

Let me know if there's any other info I can share to help troubleshoot this one, and thanks again for the amazing work you to with this plugin!

**Comment by nitaybz** [comment]
there was a bug in the code, but it's solved now! sorry for the delay...
install homebridge-tado-ac@2.2.12
with
`sudo npm install -g homebridge-tado-ac`

**Comment by jadomski** [comment]
Thanks! You’re a legend!
