### ISSUE TITLE
Support for more than  1 Tado AC unit

### ISSUE THREAD

**Issue by kaiatkins** [nitaybz/homebridge-tado-ac#22]
Does it support more than 1 unit in a house in different rooms?

**Comment by nitaybz** [comment]
yes, it will detect your other devices automatically....

**Comment by kaiatkins** [comment]
So I can control 3 Tado AC units in my house through home kit?

**Comment by nitaybz** [comment]
definitely! that's exactly whats going on in my house

**Comment by kaiatkins** [comment]
Awesome thanks 🙏
