### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by dima-bzz** [nitaybz/homebridge-tado-ac#23]
Hi. Why is it that in automation you cannot use the temperature sensors and humidity?

**Comment by nitaybz** [comment]
in Home app there is no such option to set automations based on the temperature or humidity.
but that can be achieved with 'Eve' app which has much more automations possibilities.

something you should consider, the temperature and humidity are not getting updated automatically, they are only updated when the app is opened or the value is part of a condition in automation, but it will not work as a trigger !

for the trigger you can use [homebridge-trigger](https://www.npmjs.com/package/homebridge-trigger) which is a plugin that made specifically to trigger a check of conditions (like temperature) every n seconds.

I hope everything is clear...

**Comment by dima-bzz** [comment]
Thank you. I understood and already found in Eve how to do this, but for some reason I can not change the value of the sensor humidity. What could be the problem?

**Comment by nitaybz** [comment]
please try to install from here:
`sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac`

if it will fix the issue I will update on npm

let me know please

**Comment by dima-bzz** [comment]
Thanks you. Now it works fine. And more one question. Why in the home screen Home Kit Humidity is displayed (Humidity in room "Room": 30%) and the temperature (Room: 25 C)?

**Comment by nitaybz** [comment]
I think it’s a Home app issue... what is the name of you device in tado? And what is the room name?

**Comment by dima-bzz** [comment]
Name is tado “Home”. Name is room “Room”. But all name is Russian!

**Comment by dima-bzz** [comment]
Name in tado “Home”. Name room “Room”. But all names in Russian!

**Comment by nitaybz** [comment]
So that’s probably the issue... my plugin can’t copy your Russian text from Tado app... but you can easily rename the devices in home app to be in Russian and that should solve your issue I think

**Comment by nitaybz** [comment]
And if the name of your room is “Room” so I guess it make sense you see humidity in room “Room”: 30%.
The main home screen status only shows the room in which the measurements were taken and not the devices themselves

**Comment by dima-bzz** [comment]
I have renamed the Home Kit for the Russian language. With the humidity, everything is fine. It's the temperature sensor. He writes (room Temperature 25C) according to the humidity sensor!
In English
![img_ad1c3ecc571f-1](https://user-images.githubusercontent.com/8027583/35997400-6fc4691e-0d2a-11e8-9d38-b2bce280e9d1.jpeg)
In Russina
![img_3d1e5e4cceb7-1](https://user-images.githubusercontent.com/8027583/35997491-b34bf828-0d2a-11e8-8a5d-1d6797229863.jpeg)

**Comment by nitaybz** [comment]
I'm not sure I understand... your humidity show 34% so hoe come the temperature is according to the humidity?

**Comment by dima-bzz** [comment]
Why have written humidity (Room humidity) but the temperature just (Room) and not (Room temperature).And when I ask what is the temperature in the room, Siri gives me the readings of the air conditioner, not the temperature sensor.

**Comment by nitaybz** [comment]
For the first question you asked, I guess that’s how home app writes the status... it does not give the word “temperature” like the humidity have, I guess it’s because of the degree sign which is for temperature mostly while percentages are used by other devices.

Regarding your second question I had this problem before but I solved when I updated iOS to the latest version

**Comment by dima-bzz** [comment]
Thanks for the help. iOS has been updated to the latest version. Perhaps this is due to localization or something.

**Comment by nitaybz** [comment]
for some reason now I'm not getting any temperature from siri... but i'm sure it's an iOS issue...

**Comment by nitaybz** [comment]
anyway, seems like this issue is solved.... so I'm closing :)
