### ISSUE TITLE
Ask Siri to adjust temp

### ISSUE THREAD

**Issue by L3x1c0n** [nitaybz/homebridge-tado-ac#25]
Should I be able o ask Siri to adjust the setting to a specific temperature?

**Comment by nitaybz** [comment]
yes you can... you can ask her:
"Set The Bedroom AC to 22 degrees"

**Comment by L3x1c0n** [comment]
I’m not sure if I’m doing something wrong but I couldn’t get that to work. 

Obviously, right now there seems to be an ongoing issue with the api and I can’t command anything. 

Can you elaborate on how to normally get this working?

**Comment by nitaybz** [comment]
install the latest version... there is a fix..
as for Siri... it should work as I said before...

**Comment by nitaybz** [comment]
there is a good picture in this page showing how to make Siri change the degrees:
[https://francisuniverse.wordpress.com/2018/01/06/how-to-add-homekit-to-your-tado-smartac-2/](https://francisuniverse.wordpress.com/2018/01/06/how-to-add-homekit-to-your-tado-smartac-2/)

**Comment by L3x1c0n** [comment]
Cool. I’m sure it’s something on my end. Feel free to close down this issue. Hanks again for being on top of the other fix. Appreciate the good work.

**Comment by jnchman** [comment]
![img_ac2ef6c7058b-1](https://user-images.githubusercontent.com/2309610/38399441-c781494e-398d-11e8-8e8d-f3a7e133b763.jpeg)
![img_b315448dd9a5-1](https://user-images.githubusercontent.com/2309610/38399449-d175aecc-398d-11e8-9c74-8ca21e380922.jpeg)

Hi there! I have the same issue.
What's interesting is that I can set AC temperature ranges, but not the target temperature.

In the above case, setting the range between 18 and 20 degrees, actually sets the target temperature to 20 degrees; the higher number.

**Comment by nitaybz** [comment]
it seems like the new iOS 11.3 has changes some stuff with Siri-Homekit...

I'll need to investigate it and maybe research on the main HAP library to see if they already adapted...

**Comment by pr1son3r** [comment]
might be that , im having issues where the device is detected but the commands are not given from the device. eg. i ask siri to turn ac off, it says its off. The Homebrige (see screenshot) says ac is off. But the Tado Smart Ac doesnt give the signal to the ac.
![1](https://user-images.githubusercontent.com/13213797/38834386-c5beb82e-41e1-11e8-8bcf-ba4c01ef7841.png)

**Comment by nitaybz** [comment]
@pr1son3r your issue is solved in the last version,

Regarding Siri commands, I can't fix it yet until someone will change something in the main HAP library.
so the workaround for not is telling Siri a range, that can include the same degree, see examples above.

Closing...
