### ISSUE TITLE
Can read the info from Tado but can't send commands to it

### ISSUE THREAD

**Issue by Francis2b** [nitaybz/homebridge-tado-ac#26]
Hi,

Today I ran into a problem, the public has trouble to send commands to Tado. When I try to turn the AC on or to change any settings, the status is updated well displayed in the Home app but nothing is sent to Tado and to the AC and when I exit the Home app and come back the status is back to off.

When I use Tado app to change the settings the AC receives the command and in the Home app I can see it has detected the changes. I suspect homebridge-tado-ac has some kind of problem in sending command but is still able to read.

I already tried to update Rasbian, packages, node, homebridge and homebridge-tado-ac but nothing has changed I'm still unable to send command to Tado.

Here is the startup log: https://pastebin.com/9p4QWF60

Thanks,

**Comment by ronnieliew** [comment]
I'm facing similar issues — no error messages on the log and error log for homebridge.
HomeKit app is able to reflect the correct status of the AC but commands to ON/OFF don't work. 

Anyway to tell if Tado might have changed their API? The commands just stopped working today.

**Comment by st1cky** [comment]
Something must have changed as I too am having trouble since today.

**Comment by nitaybz** [comment]
Maybe they change the api... I will take a look

**Comment by cooksimo** [comment]
Same issue here - I notice the tado app was updated 3 days ago so definitely looks like their API must have changed.

**Comment by taimurasad** [comment]
same issue here. was working fine for months until yesterday where I am unable to send commands. any update @nitaybz ?

**Comment by L3x1c0n** [comment]
This. Just in the last 12 or so hours.

**Comment by stadtmensch** [comment]
Yes, same here, since yesterday it does not works anymore. I see on the console "Activating Air Conditioning AC" but nothing happens. I guess they changed something at the API, because there was an update on my iPhone app, yesterday.

**Comment by jadomski** [comment]
I've been seeing this for about 24 hours as well. No errors showing in Homebridge logs either.

**Comment by taimurasad** [comment]
any update @nitaybz ?

**Comment by nitaybz** [comment]
I tried to solve it but I couldn’t... I’ll try to contact their support to see if they can help me with that...
Sorry guys!

**Comment by Francis2b** [comment]
Thanks @nitaybz! Tado° wrote on theire website they plan to open the API to the devs in the upcoming months, maybe they will help you.

**Comment by grork** [comment]
@nitaybz is the API / request just returning 'yep! did it!', or are there errors?

**Comment by nitaybz** [comment]
I fixed the API issue!!
and added 2 new features to disable fans and/or humidity sensors... check the readme file for more info...
install the new version (2.3) at:
`sudo npm install -g homebridge-tado-ac`

Let me know that it works for all of you guys!

**Comment by Francis2b** [comment]
It works but when you want to set the AC to Cool in fact it set it to Heat. The mode switch from cool to heat very quickly and it's the same for Auto.

**Comment by nitaybz** [comment]
@Francis2b it works ok for me... try to do the following:
1. stop homebridge
2. delete the Tado related files from the persist folder.
3. restart homebridge

**Comment by Francis2b** [comment]
what do you mean by "the persist folder" ?

**Comment by nitaybz** [comment]
where the config file is, there is a folder named 'persist'
Delete the files there that are related to your Tado devices... you should see it in the file name

**Comment by Francis2b** [comment]
oh ok sorry! By the way, now homebridge doesn't automatically start :/

**Comment by nitaybz** [comment]
I'm not sure how you are running your homebridge so I can't help you with that... but the update itself should not change the way your homebridge starts...

**Comment by Francis2b** [comment]
I'm using Screen but it might not be the best way. Any advice?

**Comment by nitaybz** [comment]
I used this guide:
https://timleland.com/setup-homebridge-to-start-on-bootup/

**Comment by Francis2b** [comment]
Ok thanks now I can switch the mode correctly!...
....
I have hard time to make homebridge to start on bootup even with the guide you send me :/

**Comment by nitaybz** [comment]
contact me on my email... you already have it... let me know where you got stuck and I'll try to help tomorrow.

**Comment by Francis2b** [comment]
Thanks ;) I'll try to solve it and I let you know thanks again

**Comment by st1cky** [comment]
Thank you, I can confirm this has fixed the problem for me.

**Comment by ronnieliew** [comment]
@nitaybz Thanks — can confirm this works.

Looks like Tado implemented a check for tokens?

**Comment by nitaybz** [comment]
this was actually implemented a long time ago, but I noticed it wasn't required so I removed it... I guess they made it required now... also I had to use some headers in the call.

**Comment by taimurasad** [comment]
Everything works perfectly now after the update. Thank you @nitaybz

**Comment by sifield** [comment]
@nitaybz thanks for all your work on creating and maintaining this plugin, all up and running again.

**Comment by stadtmensch** [comment]
It works again. Great! Thank you!

**Comment by pinni74** [comment]
Fixed the issue thanks! But now. I can’t ask Siri to change the Temperature like I could before. Any thoughts?

**Comment by jnchman** [comment]
@pinni74 
Same problem here. When telling Siri to "Set the Bedroom AC Temperature to 20 degrees", Siri just responds with "Sorry, I wasn't able to find anything like that in your home this time."

Turning the AC on/off works perfectly fine.

**Comment by jadomski** [comment]
My brother had that problem after updating to the latest iOS. He found that turning Siri off and back on again resolved it for him.

**Comment by jnchman** [comment]
@iJaffa Thanks for the tip. Unfortunately turning Siri on and off didn't seem to work for me. Telling Siri: "Turn off the Bedroom AC" works perfectly fine. Which means that it recognises and can communicate with the homebridge plugin by name. But it seems to not know about the heating/cooling target temperature characteristic.

**Comment by pinni74** [comment]
It could never tell you the temperature of the room off the tado unit either?

**Comment by nitaybz** [comment]
it all seems like a bug in Siri... and not the plugin, cause you said it does recognize the device with power. can it be an iOS 11.3 bug?
does all of you have this version at least?

**Comment by pinni74** [comment]
I’ve had iOS 11.3 beta and GM prior to this issue and it was ok. 11.4 beta doesn’t help either.

**Comment by pinni74** [comment]
Broken again? Anyone else having the same conditions as we did before the update?

**Comment by jnchman** [comment]
@pinni74 Yeah there seems to be an issue with the latest version 2.3.2. It seems rolling back to 2.3.1 fixes this.

**Comment by taimurasad** [comment]
hmm seems to be working fine for me. Anyone else having this problem?
