### ISSUE TITLE
Asking Siri for the temperature gives me the setting of the AC

### ISSUE THREAD

**Issue by cooksimo** [nitaybz/homebridge-tado-ac#27]
This changed when I updated from the old version to the new one. Previously when I asked siri what the temperature in a room was it would tell me the current temperature.

With the new version, it now replies: "The AC is at 17 degrees" - which is not true, it's not even turned on.

Any way to get the old behaviour back?

**Comment by nitaybz** [comment]
this is an issue with apple... not with the plugin... I'm experiencing the same issues.
It was fixed for a while but now it's broken again and i'm not sure I can do anything about it...

**Comment by nitaybz** [comment]
seems like Siri is giving the correct value... @cooksimo can you confirm?

**Comment by cooksimo** [comment]
Yep, it works for me now, thanks!
