### ISSUE TITLE
Current temperature

### ISSUE THREAD

**Issue by dima-bzz** [nitaybz/homebridge-tado-ac#28]
The current temperature has disappeared! How to fix it?

**Comment by nitaybz** [comment]
still?

**Comment by dima-bzz** [comment]
![e714ad77-f9a4-4f5c-8907-6a9d243ed3d2](https://user-images.githubusercontent.com/8027583/39739216-7821b0c2-5298-11e8-84e1-dc8292670181.jpeg)

Yes. The installed version 2.3.0 just disappeared from the screen current temperature.

**Comment by dima-bzz** [comment]
I updated to 2.3.3 but the current temperature is not

**Comment by nitaybz** [comment]
seems like the current temperature is 25 deg

**Comment by dima-bzz** [comment]
Earlier there was a separate icon is the same as the humidity. But after the update it disappeared and the current temperature is now only on the air conditioner control icon.

**Comment by nitaybz** [comment]
Hey Dima!

I removed that extra temperature sensor from the since it didn't have any advantage, I thought it would solve the Siri issue but it didn't.
