### ISSUE TITLE
error cause restart from Homebridge (one time a day) ??

### ISSUE THREAD

**Issue by roe1974** [nitaybz/homebridge-tado-ac#29]
hi

i found this in my log today.....
what cause this error ?

Apr 02 16:37:56 raspberrypi homebridge[22059]: events.js:183
Apr 02 16:37:56 raspberrypi homebridge[22059]: throw er; // Unhandled 'error' event
Apr 02 16:37:56 raspberrypi homebridge[22059]: ^
Apr 02 16:37:56 raspberrypi homebridge[22059]: Error: getaddrinfo ENOTFOUND auth.tado.com auth.tado.com:443
Apr 02 16:37:56 raspberrypi homebridge[22059]: at errnoException (dns.js:50:10)
Apr 02 16:37:56 raspberrypi homebridge[22059]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

regards, richard

**Comment by roe1974** [comment]
today the same again ?!?!?!?!

Apr 03 06:37:13 raspberrypi homebridge[1569]: events.js:183
Apr 03 06:37:13 raspberrypi homebridge[1569]: throw er; // Unhandled 'error' event
Apr 03 06:37:13 raspberrypi homebridge[1569]: ^
Apr 03 06:37:13 raspberrypi homebridge[1569]: Error: getaddrinfo ENOTFOUND auth.tado.com auth.tado.com:443
Apr 03 06:37:13 raspberrypi homebridge[1569]: at errnoException (dns.js:50:10)
Apr 03 06:37:13 raspberrypi homebridge[1569]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

regards RIchard

**Comment by nitaybz** [comment]
do you have the latest version installed?

**Comment by nitaybz** [comment]
install the latest version (2.3.2)... should be fixed

**Comment by roe1974** [comment]
yes, it was the latest.....will test 2.3.2 :-)
thx
Richard
