### ISSUE TITLE
Can read put can't change settings

### ISSUE THREAD

**Issue by Francis2b** [nitaybz/homebridge-tado-ac#30]
Hi,

Since today I ran into a bug, I was able to change the temperature of the current mode, I can turn my AC ON and OFF but I can't change mode. To change mode I need to go to the Tado app change mode.

So, I updated to the last version of the plugin and I did a `sudo apt-get update` and a `sudo apt-get upgrade`. I also delete the Tado related files from the persist folder

And now I the plugin can only read the status of Tado but can't change any settings. It looks like #26 is back.

I'm guessing Tado is working on the API...

Thanks,

**Comment by beergut** [comment]
Yes. I got this as well. I managed to get at least "swtich" to turn off my AC, and that was about what I can do using Home App --> Tado controls.

**Comment by jadomski** [comment]
I can confirm that it is impacting me too.

It seems like it is able to successfully read the current status being sent from the Tado side, and it appears that the commands are being successfully sent from the Home and Homebridge side, but nothing changes on the Tado itself.

```
homebridge[1014]: [2018-4-10 15:48:05] [Tado AC] My Home Mode is OFF
homebridge[1014]: [2018-4-10 15:48:05] [Tado AC] My Home Current Temperature is 27.58ºC
```

Refreshing the Home app confirms that nothing has been changed and shows the correct status.

**Comment by nitaybz** [comment]
which version are you running?
try to install previous versions like:
`sudo npm install -g homebridge-tado-ac@2.3.1`
or
`sudo npm install -g homebridge-tado-ac@2.3`

see if that helps cause in the next 2 weeks I won't be able to test it myself...

**Comment by jadomski** [comment]
I was running version 2.3.2 which was not working.

Version 2.3.1 is working again for me though.

I haven't tried 2.3.0 since 2.3.1 is working.

**Comment by nitaybz** [comment]
So i probably destroyed something in the last version... I'll take a look :)
thanks

**Comment by beergut** [comment]
I will try this when I get home on 2.3.1. Thanks

**Comment by Francis2b** [comment]
Same problem with 2.3.1 and with 2.3.0 Home can't find my AC

**Comment by pinni74** [comment]
Mine is was ok with latest build till today. Broken again stuck on my last setting.

**Comment by nitaybz** [comment]
Hey Guys!
Sorry for the late response... 
We finally moved to our new house and I had the chance to install the Tado devices and fix the latest error that prevented commands from being sent...

Install the latest version (2.3.3) from npm with:
`sudo npm install -g homebridge-tado-ac`

Please confirm that everything works as expected...
Thanks!

**Comment by Francis2b** [comment]
Hi @nitaybz congratulations for the new house!

Thanks to the last update everything seems to work great now!

Thanks a lot!

**Comment by nitaybz** [comment]
Thanks @Francis2b !

Closing...
