### ISSUE TITLE
Inquiry: LG SmartThinQ Air Con

### ISSUE THREAD

**Issue by kaiatkins** [nitaybz/homebridge-tado-ac#32]
I didnt know a way to contact so I am creating an issue here.

I have the  LG Q12JA2PA Air Conditioner with the LG SmartThinQ 

Can you or know of anyone that can help connect homebridge with LG SmartThinQ to control like the Tado?

Thank you for your time!

**Comment by nitaybz** [comment]
I don't have that air conditioner so I definitely can't help with that, maybe you should look for an answer in the main [Homebridge](https://github.com/nfarina/homebridge/issues) Thread.
