### ISSUE TITLE
Devices not showing in Home app

### ISSUE THREAD

**Issue by aterrett** [nitaybz/homebridge-tado-ac#33]
Hi there

I've installed the Tado AC plugin, but when I launch Homebridge via the terminal and scan the code into the Home app, only the "Homebridge" itself is added to the Home app. 

I've marked the "weatherSensorsEnabled" item false, but have otherwise followed the instructions on the main page.

Any ideas?

Cheers
AT

![terminal](https://user-images.githubusercontent.com/38714835/39228877-8a1f9a86-48a3-11e8-970c-6ff430d8119b.jpg)

**Comment by martijnmnnk** [comment]
There seems to be a bug in the latest version in the plugin. Try to downgrade to a previous version with this command:

sudo npm install -g homebridge-tado-ac@2.3.1

**Comment by aterrett** [comment]
Gave that a try but no difference I’m afraid. 

I also tried uninstalling the original plugin and then installing that version clean - no dice. 

Thanks for your help though.

**Comment by nitaybz** [comment]
please show your config... seems like it's not recognizing any device... might be   a homeID issue

**Comment by aterrett** [comment]
Thanks very much. See below.

I haven't updated the homeID - thought the app gets this automatically?

![config](https://user-images.githubusercontent.com/38714835/39241854-96fb8f94-48cb-11e8-89d3-aaeb698bd8c9.jpg)

**Comment by nitaybz** [comment]
that's the issue my friend... remove the HomeID row... this will be the only way that the system will recognize the real homeID

**Comment by aterrett** [comment]
Ha!  Thank you!

**Comment by nitaybz** [comment]
sure :) no problem
