### ISSUE TITLE
Home App Icons

### ISSUE THREAD

**Issue by beergut** [nitaybz/homebridge-tado-ac#34]
Hello,

I got Tado AC working (mostly), but is very curious to know what those 3 different icons that appear on Home App. How are they different? and how can use them?

![image](https://user-images.githubusercontent.com/82722/39347714-babc1726-4a26-11e8-8a40-b7aef7dc39e5.png)

**Comment by nitaybz** [comment]
AC Fan - is the control of your fan mode in your AC
AC AC - is the control of your AC's Cool/Heat/Auto modes and it also provides room temperature measurements.
AC Humidity - is the humidity measured by the Tado device
AC Manual Control - is the switch to turn off/on Tado's manual control

you can remove most of them if you don't use them, check the readme to see how.

**Comment by nitaybz** [comment]
closing
