### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by beergut** [nitaybz/homebridge-tado-ac#35]
Hello,

I am quite new to this, but I was wondering how can i write any automation scripts using (temperature, humidity, time, and external temperature ... etc)?

Thanks

**Comment by nitaybz** [comment]
This question will probably be more suitable in the main [Homebridge](https://github.com/nfarina/homebridge/issues) thread I believe, but I'll answer anyway.

With automation it's all about triggers and conditions.
To make automations based on change of humidity or temperature it's best to use "EVE" app, there you can set the automation to be triggered by any change in humidity/temperature and the condition should be anywhere above or below a specific value you'll set, all that can only happen if the status of the sensor is changing and reporting change even when you're app closed, it's called polling.
in this plugin, I don't poll for status frequently but only when you open the home app, that issue can be bridged by using a specific homebridge plugin called [homebridge-trigger](https://www.npmjs.com/package/homebridge-trigger), you can read there how to use it.

I hope this make some sense... let me know if you have any more questions.
