### ISSUE TITLE
Homekit commands will not be executed in V2.3.2

### ISSUE THREAD

**Issue by Partyboy97** [nitaybz/homebridge-tado-ac#36]
Hi

all commands from the Homekit app are not executed. In the log of homebridge all status changes appear, but nothing happens. From the Tado app, the AC can be controlled normally and the status is also displayed correctly in the Homekit app. Any ideas? Basically it works, but not via Homekit.

iOS11.4 Public Beta / tvOS Beta

**Comment by cw1812** [comment]
Can try previous version:

sudo npm install -g homebridge-tado-ac@2.3.0

Mine work in 2.3.0, not work in 2.3.1 & 2.3.2.

**Comment by Partyboy97** [comment]
I tried the follow versions 2.0.2 2.1.3 2.3.0 2.3.2. For me it seems like 2.3.1 is working ..

**Comment by nitaybz** [comment]
Hey Guys!
Sorry for the late response... 
We finally moved to our new house and I had the chance to install the Tado devices and fix the latest error that prevented commands from being sent...

Install the latest version (2.3.3) from npm with:
`sudo npm install -g homebridge-tado-ac`

Please confirm that everything works as expected...
Thanks!

**Comment by martijnmnnk** [comment]
I've installed version 2.3.2, and can confirm that the problems have been fixed. Thank you for your hard work!

**Comment by Partyboy97** [comment]
Confirm problem have been solved in 2.3.3.
