### ISSUE TITLE
No Fan in HK

### ISSUE THREAD

**Issue by roe1974** [nitaybz/homebridge-tado-ac#37]
Hi

i currently use this settings in homebridge

    "platform": "TadoAC",
    "name": "Tado AC",
    "username": "xxx@xxx.xx",
    "password": "xxxxxxxx",
    "homeID": xxxxxx,
    "anyoneSensor": false

i have the humidty sensor in HK but no Fan accessorie ?
is this due to the thermostatic mode i use with TADO AC or the new version 2.3.3 ?

Richard

**Comment by nitaybz** [comment]
Yes, the plugin currently not supporting thermostatic control... usually it detects automatically the capabilities of your ac but with thermostatic control there are no capabilities

**Comment by roe1974** [comment]
Ok, thx for Info
Richard
