### ISSUE TITLE
[Tado AC] Getting Token...

### ISSUE THREAD

**Issue by roe1974** [nitaybz/homebridge-tado-ac#38]
Hi
Is it nomral, that i see permanent

[TADO AC] Getting Token....

in the log ?  .. as for example:

May 09 00:04:36 homebridge-raspi homebridge[531]: [2018-5-9 00:04:36] [Tado AC] Getting Token...
May 09 00:12:56 homebridge-raspi homebridge[531]: [2018-5-9 00:12:56] [Tado AC] Getting Token...
May 09 00:21:16 homebridge-raspi homebridge[531]: [2018-5-9 00:21:16] [Tado AC] Getting Token...
May 09 00:29:36 homebridge-raspi homebridge[531]: [2018-5-9 00:29:36] [Tado AC] Getting Token...
May 09 00:37:56 homebridge-raspi homebridge[531]: [2018-5-9 00:37:56] [Tado AC] Getting Token...
May 09 00:46:16 homebridge-raspi homebridge[531]: [2018-5-9 00:46:16] [Tado AC] Getting Token...
May 09 00:54:36 homebridge-raspi homebridge[531]: [2018-5-9 00:54:36] [Tado AC] Getting Token...
May 09 01:02:56 homebridge-raspi homebridge[531]: [2018-5-9 01:02:56] [Tado AC] Getting Token...
May 09 01:11:16 homebridge-raspi homebridge[531]: [2018-5-9 01:11:16] [Tado AC] Getting Token...
May 09 01:19:36 homebridge-raspi homebridge[531]: [2018-5-9 01:19:36] [Tado AC] Getting Token...
May 09 01:27:56 homebridge-raspi homebridge[531]: [2018-5-9 01:27:56] [Tado AC] Getting Token...
May 09 01:36:16 homebridge-raspi homebridge[531]: [2018-5-9 01:36:16] [Tado AC] Getting Token...
May 09 01:44:36 homebridge-raspi homebridge[531]: [2018-5-9 01:44:36] [Tado AC] Getting Token...
May 09 01:52:56 homebridge-raspi homebridge[531]: [2018-5-9 01:52:56] [Tado AC] Getting Token...
May 09 02:01:16 homebridge-raspi homebridge[531]: [2018-5-9 02:01:16] [Tado AC] Getting Token...
May 09 02:09:36 homebridge-raspi homebridge[531]: [2018-5-9 02:09:36] [Tado AC] Getting Token...
May 09 02:17:56 homebridge-raspi homebridge[531]: [2018-5-9 02:17:56] [Tado AC] Getting Token...
May 09 02:26:16 homebridge-raspi homebridge[531]: [2018-5-9 02:26:16] [Tado AC] Getting Token...
May 09 02:34:36 homebridge-raspi homebridge[531]: [2018-5-9 02:34:36] [Tado AC] Getting Token...
May 09 02:42:56 homebridge-raspi homebridge[531]: [2018-5-9 02:42:56] [Tado AC] Getting Token...
May 09 02:51:16 homebridge-raspi homebridge[531]: [2018-5-9 02:51:16] [Tado AC] Getting Token...
May 09 02:59:36 homebridge-raspi homebridge[531]: [2018-5-9 02:59:36] [Tado AC] Getting Token...
May 09 03:07:56 homebridge-raspi homebridge[531]: [2018-5-9 03:07:56] [Tado AC] Getting Token...
May 09 03:16:16 homebridge-raspi homebridge[531]: [2018-5-9 03:16:16] [Tado AC] Getting Token...
May 09 03:24:36 homebridge-raspi homebridge[531]: [2018-5-9 03:24:36] [Tado AC] Getting Token...
May 09 03:32:56 homebridge-raspi homebridge[531]: [2018-5-9 03:32:56] [Tado AC] Getting Token...
May 09 03:41:16 homebridge-raspi homebridge[531]: [2018-5-9 03:41:16] [Tado AC] Getting Token...
May 09 03:49:36 homebridge-raspi homebridge[531]: [2018-5-9 03:49:36] [Tado AC] Getting Token...
May 09 03:57:56 homebridge-raspi homebridge[531]: [2018-5-9 03:57:56] [Tado AC] Getting Token...
May 09 04:06:16 homebridge-raspi homebridge[531]: [2018-5-9 04:06:16] [Tado AC] Getting Token...
May 09 04:14:36 homebridge-raspi homebridge[531]: [2018-5-9 04:14:36] [Tado AC] Getting Token...
May 09 04:22:56 homebridge-raspi homebridge[531]: [2018-5-9 04:22:56] [Tado AC] Getting Token...
May 09 04:31:16 homebridge-raspi homebridge[531]: [2018-5-9 04:31:16] [Tado AC] Getting Token...
May 09 04:39:36 homebridge-raspi homebridge[531]: [2018-5-9 04:39:36] [Tado AC] Getting Token...

Richard

**Comment by nitaybz** [comment]
Yes, it’s getting the token every 8 minutes.
I’ll remove the log of it in the next version

**Comment by roe1974** [comment]
Ok, thx for Info
Richard
