### ISSUE TITLE
Crash when sending commands from the homekit app

### ISSUE THREAD

**Issue by alucarddelta** [nitaybz/homebridge-tado-ac#4]
An error occurs when sending any command from the homekit app. Below are 2 sample outputs when trying to preform 2 different action.

I am running Homebridge on Ubuntu 16.04.2 LTS

```
[6/10/2017, 2:39:39 PM] [Tado AC] Setting Lounge room AC to COOL
/usr/local/lib/node_modules/homebridge-tado-ac/index.js:897
                accessory.FanService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.INACTIVE);
                                    ^

TypeError: Cannot read property 'getCharacteristic' of undefined
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:897:37)
    at Timer.listOnTimeout (timers.js:92:15)
```

&

```
[6/10/2017, 2:50:40 PM] [Tado AC] Turning OFF Lounge room AC
/usr/local/lib/node_modules/homebridge-tado-ac/index.js:893
                accessory.FanService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.INACTIVE);
                                    ^

TypeError: Cannot read property 'getCharacteristic' of undefined
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:893:37)
    at Timer.listOnTimeout (timers.js:92:15)
```
Below is the platform config

```
    {
        "platform": "TadoAC",
        "name": "Tado AC",
        "username": "****",
        "password": "****",
        "tadoMode": "TADO_MODE"
    }
```

**Comment by alucarddelta** [comment]
Tried removing the mode option, no change.

**Comment by nitaybz** [comment]
@alucarddelta please try to install from GIT last version:
`sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac`

**Comment by nitaybz** [comment]
if it's working I'll push to npm

**Comment by alucarddelta** [comment]
That seemed to have worked regarding that error, and I can now enable/disable/change temp. 

However trying there seems to be an issue with Auto mode now. When you try to enable it, it will auto switch back to cool mode. Checking to see if its a config issue.

**Comment by nitaybz** [comment]
do you have Auto mode in your AC?
cause if not, it make sense...

**Comment by alucarddelta** [comment]
I do. But Tado might not have detected it. I'll live. Thanks for the quick update.

**Comment by nitaybz** [comment]
if you don't have Auto mode in Tado app then you won't be able to control it within Home app... and the mode will turn back to Cool

**Comment by nitaybz** [comment]
@alucarddelta is it the situation? can you control Auto mode from Tado app?
