### ISSUE TITLE
Error "get Token" .... hombridge crash

### ISSUE THREAD

**Issue by roe1974** [nitaybz/homebridge-tado-ac#40]
Hi

Every Time when the "get Token" dont work, my homebridge crashes and restarts (system.d)
see log below ... is this normal ?

May 13 07:03:48 homebridge-raspi homebridge[4379]: { Error: getaddrinfo ENOTFOUND auth.tado.com auth.tado.com:443
May 13 07:03:48 homebridge-raspi homebridge[4379]: at errnoException (dns.js:50:10)
May 13 07:03:48 homebridge-raspi homebridge[4379]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
May 13 07:03:48 homebridge-raspi homebridge[4379]: code: 'ENOTFOUND',
May 13 07:03:48 homebridge-raspi homebridge[4379]: errno: 'ENOTFOUND',
May 13 07:03:48 homebridge-raspi homebridge[4379]: syscall: 'getaddrinfo',
May 13 07:03:48 homebridge-raspi homebridge[4379]: hostname: 'auth.tado.com',
May 13 07:03:48 homebridge-raspi homebridge[4379]: host: 'auth.tado.com',
May 13 07:03:48 homebridge-raspi homebridge[4379]: port: 443 }
May 13 07:03:48 homebridge-raspi homebridge[4379]: Fetching Token failed - Trying again...
May 13 07:03:58 homebridge-raspi homebridge[4379]: /usr/lib/node_modules/homebridge-tado-ac/index.js:73
May 13 07:03:58 homebridge-raspi homebridge[4379]: getToken()
May 13 07:03:58 homebridge-raspi homebridge[4379]: ^
May 13 07:03:58 homebridge-raspi homebridge[4379]: ReferenceError: getToken is not defined
May 13 07:03:58 homebridge-raspi homebridge[4379]: at Timeout._onTimeout (/usr/lib/node_modules/homebridge-tado-ac/index.js:73:17)
May 13 07:03:58 homebridge-raspi homebridge[4379]: at ontimeout (timers.js:482:11)
May 13 07:03:58 homebridge-raspi homebridge[4379]: at tryOnTimeout (timers.js:317:5)
May 13 07:03:58 homebridge-raspi homebridge[4379]: at Timer.listOnTimeout (timers.js:277:5)

regards, Richard

**Comment by nitaybz** [comment]
I'll fix it

**Comment by roe1974** [comment]
OK, perfect 👍

**Comment by nitaybz** [comment]
sorry for the long wait... it should not crush homebridge now...
