### ISSUE TITLE
Homebridge crash still not fixed.....

### ISSUE THREAD

**Issue by roe1974** [nitaybz/homebridge-tado-ac#41]
just updated to 2.3.4 yesterday........ last night, see the log for another crash:

Jun 01 05:23:01 homebridge-raspi homebridge[525]: { Error: getaddrinfo ENOTFOUND auth.tado.com auth.tado.com:443
Jun 01 05:23:01 homebridge-raspi homebridge[525]: at errnoException (dns.js:50:10)
Jun 01 05:23:01 homebridge-raspi homebridge[525]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
Jun 01 05:23:01 homebridge-raspi homebridge[525]: code: 'ENOTFOUND',
Jun 01 05:23:01 homebridge-raspi homebridge[525]: errno: 'ENOTFOUND',
Jun 01 05:23:01 homebridge-raspi homebridge[525]: syscall: 'getaddrinfo',
Jun 01 05:23:01 homebridge-raspi homebridge[525]: hostname: 'auth.tado.com',
Jun 01 05:23:01 homebridge-raspi homebridge[525]: host: 'auth.tado.com',
Jun 01 05:23:01 homebridge-raspi homebridge[525]: port: 443 }
Jun 01 05:23:01 homebridge-raspi homebridge[525]: Fetching Token failed - Trying again...
Jun 01 05:23:11 homebridge-raspi homebridge[525]: /usr/lib/node_modules/homebridge-tado-ac/index.js:66
Jun 01 05:23:11 homebridge-raspi homebridge[525]: var lastToken = self.storage.getItem('Tado_Token');
Jun 01 05:23:11 homebridge-raspi homebridge[525]: ^
Jun 01 05:23:11 homebridge-raspi homebridge[525]: TypeError: Cannot read property 'storage' of undefined
Jun 01 05:23:11 homebridge-raspi homebridge[525]: at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado-ac/index.js:66:38)
Jun 01 05:23:11 homebridge-raspi homebridge[525]: at emitNone (events.js:111:20)
Jun 01 05:23:11 homebridge-raspi homebridge[525]: at IncomingMessage.emit (events.js:208:7)
Jun 01 05:23:11 homebridge-raspi homebridge[525]: at endReadableNT (_stream_readable.js:1064:12)
Jun 01 05:23:11 homebridge-raspi homebridge[525]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
Jun 01 05:23:11 homebridge-raspi homebridge[525]: at process._tickCallback (internal/process/next_tick.js:180:9)

:-(

Richard

**Comment by roe1974** [comment]
This night again.......

Jun 05 01:20:26 homebridge-raspi homebridge[9678]: { Error: getaddrinfo ENOTFOUND auth.tado.com auth.tado.com:443
Jun 05 01:20:26 homebridge-raspi homebridge[9678]: at errnoException (dns.js:50:10)
Jun 05 01:20:26 homebridge-raspi homebridge[9678]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
Jun 05 01:20:26 homebridge-raspi homebridge[9678]: code: 'ENOTFOUND',
Jun 05 01:20:26 homebridge-raspi homebridge[9678]: errno: 'ENOTFOUND',
Jun 05 01:20:26 homebridge-raspi homebridge[9678]: syscall: 'getaddrinfo',
Jun 05 01:20:26 homebridge-raspi homebridge[9678]: hostname: 'auth.tado.com',
Jun 05 01:20:26 homebridge-raspi homebridge[9678]: host: 'auth.tado.com',
Jun 05 01:20:26 homebridge-raspi homebridge[9678]: port: 443 }
Jun 05 01:20:26 homebridge-raspi homebridge[9678]: Fetching Token failed - Trying again...
Jun 05 01:20:37 homebridge-raspi homebridge[9678]: /usr/lib/node_modules/homebridge-tado-ac/index.js:66
Jun 05 01:20:37 homebridge-raspi homebridge[9678]: var lastToken = self.storage.getItem('Tado_Token');
Jun 05 01:20:37 homebridge-raspi homebridge[9678]: ^
Jun 05 01:20:37 homebridge-raspi homebridge[9678]: TypeError: Cannot read property 'storage' of undefined
Jun 05 01:20:37 homebridge-raspi homebridge[9678]: at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado-ac/index.js:66:38)
Jun 05 01:20:37 homebridge-raspi homebridge[9678]: at emitNone (events.js:111:20)
Jun 05 01:20:37 homebridge-raspi homebridge[9678]: at IncomingMessage.emit (events.js:208:7)
Jun 05 01:20:37 homebridge-raspi homebridge[9678]: at endReadableNT (_stream_readable.js:1064:12)
Jun 05 01:20:37 homebridge-raspi homebridge[9678]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
Jun 05 01:20:37 homebridge-raspi homebridge[9678]: at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by nitaybz** [comment]
sorry... I missed something in the last update... install again please (2.3.5)

**Comment by roe1974** [comment]
update done, i will test ;-)
thx !!!!!!, richard

**Comment by roe1974** [comment]
looks good till now ;-)
i will close here
thx !! Richard
