### ISSUE TITLE
Issue When Giving Siri Commands

### ISSUE THREAD

**Issue by MrNPP** [nitaybz/homebridge-tado-ac#42]
Hi,
I’m running version 2.3.4.
When I ask Siri to change the temp in the room, be it ask her to set the Tado to XXc or turn the Tado up or down, make the room hotter, cooler etc... She gives me an error.
She reply’s ‘Sorry I can’t find anything like that in your Living Room in your home this time’.
Other commands such as telling her to set the Tado to heat/cool or on and off work. She will also tell me the room temp and that the Tado is warming the room to XXc.

Edit: I’ve updated to ver 2.3.5 and the issue persists.

**Comment by pinni74** [comment]
I have the same issue and I can’t put a finger on when or what changed that broke the functionality. It’s driving me nuts now I can’t change the temp via HomePod. Hopefully someone has an idea what causes it.

**Comment by MrNPP** [comment]
So tested this again on the weekend and Siri can now respond to temperature change commands. I had not made any changes to my system. 
Perhaps this issue was at Apple's side and Homebridge.

**Comment by pinni74** [comment]
Just tested mine and it’s still not working did you update hombridge and tado plugin?

**Comment by pinni74** [comment]
Siri doesn’t understand the connection for temprature for the tado ac it seems? But seems like it’s not happening to everyone?

**Comment by nitaybz** [comment]
suddenly it works for me as well!!
I can say to siri: "Set the Living Room AC to 24 degrees" and she does it!

**Comment by MrNPP** [comment]
So I didn't make any changes to my software.
However, this still isn't working perfectly, if I ask Siri to turn the temperature down, she acknowledges the request and says she is lowering the temp but the command sent to Tado turns it off.

**Comment by pinni74** [comment]
nope! i even tried room specifics and everything i could imagine and no love :(

**Comment by nitaybz** [comment]
Hey Guys !
Please try the new version 3, I found it solving my problem. also you have the ability to change to thermostat accessory which works a bit differently.

read the README carefully and update your plugin with:
`sudo npm install -g homebridge-tado-ac`

would love to hear your thoughts

**Comment by nitaybz** [comment]
Closing issue... if same issue persist please reopen.
