### ISSUE TITLE
Request for Auto fan mode

### ISSUE THREAD

**Issue by jadomski** [nitaybz/homebridge-tado-ac#5]
Would it be possible to add a hard coded auto fan mode that ignores the fan speed in HomeKit? The config could be something like fanSpeed=disabled and then set Tado to auto fan speed in the backend?

**Comment by nitaybz** [comment]
It’s a bit complicated... because if one of your capabilities (cool/heat/fan) does not support Auto speed, it will not send any command... but I’ll think of a way to achieve that...

**Comment by nitaybz** [comment]
Didn’t think Auto fan speed is really needed when I created this plugin :)

**Comment by jadomski** [comment]
Maybe I'm asking for something which most users won't need.

In my case my AC unit is somewhat useful when it comes to auto fan speed. When it first turns on the fan goes on high to cool down the place quickly, and then it sits on a lower setting in order to maintain a quieter environment.

**Comment by nitaybz** [comment]
check out my last version v2.2

**Comment by jadomski** [comment]
Works well, thanks for the enhancement. This is one of the best homebridge plugins 😁

**Comment by nitaybz** [comment]
I'm glad I could help :)
