### ISSUE TITLE
Crash Homekit when cooler is in dry mode

### ISSUE THREAD

**Issue by jeyremy** [nitaybz/homebridge-tado-ac#50]
Hi, 

i have see a problem : when i put the cooler in dry mode all my homebridge accessories are giving the "no response" signal of death ^^

I just figured out this but it has been doing it for a long time, without i beeing able to put m finger on it. 

The Dry mode is available from the Tado app

**Comment by nitaybz** [comment]
Hey @jeyremy  !
Version 3 will definitely solve that issue...

read the README carefully and update your plugin with:
`sudo npm install -g homebridge-tado-ac`

would love to hear your thoughts

**Comment by nitaybz** [comment]
closing.... open if problem persist
