### ISSUE TITLE
Something changed today @ TADO API.... ?!?!!?

### ISSUE THREAD

**Issue by roe1974** [nitaybz/homebridge-tado-ac#52]
Today the TADO Server was down....
After a few minutes, back online again, Homekit now has recognized the TADO AC for new..... and the Fan is not available... ?!?!?!?
Every one else the same problems ?

Richard

**Comment by nitaybz** [comment]
still have the issue?

**Comment by roe1974** [comment]
yes ... with 2.3.5 .... we will see with 3.0.x ;-)
