### ISSUE TITLE
Parameters not updating

### ISSUE THREAD

**Issue by gattol** [nitaybz/homebridge-tado-ac#54]
Hi there, i’m running 3.0.5, i’ve added parameters such like extraHumiditySensor, forceThermostat, statePollingInterval, disableFan but i can’t see updates in HomeKit app. (For example i always have the fan and can’t see the humidity sensor)
Already rebooted HomeKit and deleted and re-added Homebridge in HomeKit app.
Thx,
Luca

**Comment by nitaybz** [comment]
show me your config please

**Comment by gattol** [comment]
Here you are:

{
  "accessories" : [
    {
      "delay" : "400000",
      "name" : "DelaySwitch",
      "accessory" : "DelaySwitch"
    }
  ],
  "bridge" : {
    "username" : "CD:22:3D:E3:CE:35",
    "name" : "Homebridge",
    "pin" : "031-45-416",
    "port" : 51826
  },
  "platforms" : [
    {
      "devices" : [
        {
          "name" : "TV Camera",
          "ip" : "192.168.1.130",
          "mac" : "64:1c:b0:6f:ea:e2"
        },
        {
          "name" : "TV Soggiorno",
          "ip" : "192.168.1.158",
          "mac" : "68:27:37:AC:61:2E"
        }
      ],
      "name" : "SamsungTizen",
      "platform" : "SamsungTizen"
    },
    {
      "disableFan" : "true",
      "forceThermostat" : "true",
      "password" : "****",
      "autoOnly" : "true",
      "platform" : "TadoAC",
      "username" : "****@****.com",
      "statePollingInterval" : "10",
      "extraHumiditySensor" : "true",
      "name" : "TadoAC"
    },
    {
      "port" : "8080",
      "name" : "config",
      "sudo" : "false",
      "platform" : "config"
    }
  ]
}

**Comment by nitaybz** [comment]
remove the quotes from the true value, make it like this:
`"disableFan" : true,` -> no quotes

**Comment by nitaybz** [comment]
also remove quotes from this:
`"statePollingInterval" : 10,`

**Comment by gattol** [comment]
Worked! Thanks!

**Comment by nitaybz** [comment]
@gattol I deleted your credentials from the config you showed... next time be careful and remove your username and password from those kind of files before posting... 

Glad it worked for you :)
