### ISSUE TITLE
Humidity sensor doesn't get removed

### ISSUE THREAD

**Issue by nicktmro** [nitaybz/homebridge-tado-ac#56]
Hi,

I would like to get rid of the extra Humidity Accessory / Sensor in the Home app, but the configuration below doesn't seem to achieve that.

I am running:
node v6.9.2
homebridge 0.4.45
Latest homebridge-tado-ac 

```json
"platforms":[
		{
			"platform": "TadoAC",
			"username": "abc@def.com",
			"password": "****",
			"weatherSensorsEnabled": true,
			"weatherPollingInterval": 30,
			"tadoMode": "TADO_MODE",
			"statePollingInterval" : 30,
			"disableHumiditySensor" : false,
			"extraHumiditySensor": false
		}
]
```

Cheers,
Nick

**Comment by nitaybz** [comment]
that is super weird as this should disable both inner humidity sensor and external...
checking the code and it seems correct and I tested it myself and found it to work... are you sure this extra sensor you see belong to this plugin?

try those configs and tell me if one of them works:
```
"platforms":[
		{
			"platform": "TadoAC",
			"username": "abc@def.com",
			"password": "****",
			"weatherSensorsEnabled": true,
			"weatherPollingInterval": 30,
			"tadoMode": "TADO_MODE",
			"statePollingInterval" : 30,
			"disableHumiditySensor" : true
		}
]
```

```
"platforms":[
		{
			"platform": "TadoAC",
			"username": "abc@def.com",
			"password": "****",
			"weatherSensorsEnabled": true,
			"weatherPollingInterval": 30,
			"tadoMode": "TADO_MODE",
			"statePollingInterval" : 30
		}
]
```

**Comment by nicktmro** [comment]
A few comments:
1. I thought 
```
"disableHumiditySensor" : false,
"extraHumiditySensor": false
```
was supposed to keep the internal sensor?

2. Yes, the sensor is Tado's

3. Neither of them achieved the result I was after. If I use 
```
"disableHumiditySensor" : true
```
then I no longer get any humidity info (in Siri, or Eve app)

Cheers

**Comment by nitaybz** [comment]
`"disableHumiditySensor" : true` is meant to remove the internal sensor that's inside the settings, like this:
![zhnelyfksiirpdn ela69q_thumb_f1b](https://user-images.githubusercontent.com/16838394/49795021-a358af80-fd41-11e8-98c5-40f61657ec83.jpg)

`"extraHumiditySensor": true` is suppose to create a new sensor that is separated from the main accessory and appear as it's own accessory in Home app.

both of them are set to false as default so that means that if you remove both of the settings you should only see the internal one shown in the picture above.

**Comment by nitaybz** [comment]
Any luck?

**Comment by nicktmro** [comment]
Sadly, I tried all combinations but I cannot see the nested (internal) Current Relative Humidity. That’s what I would actually like to have. Leaving the options out completely doesn’t do it either. 

The only thing I can achieve is to remove the external sensor. Getting the internal sensor to show up is where I struggle.

**Comment by nitaybz** [comment]
How did you remove the external? At first you said you couldn’t remove it... regarding the internal one... if you’re willing to test, install homebridge version 4.38 and let me know if it works.
I can’t test it myself at the moment so if it’s a matter of homebridge version I’ll see what I can do.

**Comment by nicktmro** [comment]
"disableHumiditySensor" : true removed the sensor.

It was neither an accessory, nor a feature in the AC. I checked with Eve and Home app.

**Comment by nitaybz** [comment]
did you install homebridge 4.38?

**Comment by nicktmro** [comment]
I didn't install it. I just tried now but I don't actually know how to do that :)

**Comment by nitaybz** [comment]
`sudo npm install -g homebridge@4.38 —unsafe-perm`

**Comment by nitaybz** [comment]
@nicktmro see what I told you in issue #57 
you might not using the correct plugin version...

**Comment by nicktmro** [comment]
I just updated to the latest and it works as advertised. Not sure what happened with the plugin versions. Thanks!
