### ISSUE TITLE
Error makes Homebridge lock up

### ISSUE THREAD

**Issue by nicktmro** [nitaybz/homebridge-tado-ac#57]
I just noticed that this error makes my entire Homebridge set-up lock up (doesn't crash). I find that after a couple of minutes homebridge recovers, but the Tado accessory doesn't update. 

```
[TadoAC] Could not retrieve status from MyRoom; error: TypeError: Cannot set property 'setting' of undefined
```

Please note that I have two units, and this happens when I set one of them to Cool via the Tado app. When I query the "other" unit via the Home app, it does update. But the unit that was updated via Tado is not updating at all.

**Comment by nitaybz** [comment]
can you attach more logs to the error?

**Comment by nicktmro** [comment]
Sure. If you don't mind, is there a particular flag I should be running homebridge with?

**Comment by nitaybz** [comment]
You can add
`"debug": true` to your Tado config and you’ll get more logs

**Comment by nicktmro** [comment]
Since my last message I got this error:

```
[TadoAC] Setting Bedroom AC to COOL
/usr/local/lib/node_modules/homebridge-tado-ac/index.js:1225
                                    if (accessory.setFunctions[j].overlay.setting.power == "OFF") {
                                                                         ^

TypeError: Cannot read property 'setting' of undefined
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:1225:74)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by nitaybz** [comment]
Try to delete the zones file from the persist folder... look for files with this name format: Zone Name + Tado

Stop homebridge, delete those files and start again.. this is a temporary fix until I’ll set a checking mechanism

UPDATE: no need to delete any files anymore after the plugin version 3.1.1

**Comment by nitaybz** [comment]
hey @nicktmro it looks like you are not using an updated version of this plugin.

The lines that shows in the error is not even in the plugin's code anymore.
please make sure you update the plugin and that homebridge is using the correct plugin path
