### ISSUE TITLE
Default action (On, Off) doesn’t work for one of two devices

### ISSUE THREAD

**Issue by grork** [nitaybz/homebridge-tado-ac#59]
Until yesterday, I was running tado-ac 2.3 with two devices, and other than occasionally crashing, everything seemed to be fine. In the spirit of ‘update all the things’ over the holiday period, I upgraded to latest everything (Homebridge, Tado-ac package)

However, I now have an issue where _one_ of the two TadoACs I have no longer responds to the toggle gesture in HomeKit (e.g. tap the accessory’s icon to switch off/on with last settings). When tapping the accessory icon for it, the accessory scales, but does not change state — going into the details of the accessory, and selecting `off` or `heat` in mode, works _fine_. The other TadoAC works fine, and has no issues — tapping the accessory icon does exactly what I expect.

My configuration has no non-default values — just the user/password combination.

When I monitor the output on homebridge while tapping the accessory, the broken one shows nothing, while the the functioning one has output and toggles state. When I manually set the state (in the details for the accessory), the output looks the same as the functioning Tado. Is there an additional logging I can turn on to see if this is HomeKit side?

Of note, the accessory that is not functioning is enumerated as the first (e.g. in homebridge startup, it lists this accessory first)

**Comment by nitaybz** [comment]
Does the one that’s not working is on “thermostatic control”?

**Comment by grork** [comment]
I found where to check in the Tado App, and both are in ‘non thermostatic control’ mode. The not-quite-working device is ~1 year old.

**Comment by nitaybz** [comment]
Do you have fan speed or swing control

**Comment by grork** [comment]
The AC has both swing & fan control, but Tado is not configured as having swing control, only fan. The two tado devices are configured with the same command set/air condtitioner model.

**Comment by nitaybz** [comment]
Please add
“Debug”: true
To your config and send me some logs of the startup

**Comment by nitaybz** [comment]
“debug” and not “Debug”
My mistake

**Comment by grork** [comment]
Log is attached (with bits redacted). It looks like that `tado-ac` is detecting the non-functioning device as thermo static, despite the UI in the Tado App saying Non-Thermostatic.

[log.txt](https://github.com/nitaybz/homebridge-tado-ac/files/2716774/log.txt)

**Comment by nitaybz** [comment]
that is what I was thinking... the thermostatic control creates a thermostat accessory which lack the on/off on tap option (homekit limitation to my understanding).
can you try and switch to between non-thermostatic and thermostatic mode until they both shows as non-thermostatic in the logs? this should solve your issue.

**Comment by grork** [comment]
I reset twice (to thermostatic, and then back, two times) — first time required me to go through the full learning flow again; still seems to be returning it.

Do you think this is a case of “I should just do a factory reset on that one device, and hopefully that fixes it”. Is there a way to force `tado-ac` to use non-thermostatic, since the device is configured that way in the Tado app?

**Comment by nitaybz** [comment]
You have 2 options here...
1. To wait until I create a fix to force non-thermostatic like you suggested
2. Reset device and it should fix the issue... another similar issue was solved with device reset. I’m pretty sure it will solve it

**Comment by grork** [comment]
Doing a full ‘setup’ again resolved this issue, and it’s been working (mostly) fine since then! Thanks or the tip! Mostly = automations turn it on at 61f/heat no matter what i set it to. But that’s for another issue.
