### ISSUE TITLE
Could not retrieve home id

### ISSUE THREAD

**Issue by zelik888** [nitaybz/homebridge-tado-ac#6]
Upgraded just now from prior version that didn't use platforms but I can't get it to work, new config.json loads but I get this error:

[TadoAC] Could not retrieve Home ID, error:TypeError: Cannot read property '0' of undefined

Running on Rpi3. Anything else I can try?

**Comment by nitaybz** [comment]
Looks like your credentials are wrong... check them again and make sure you are using double quotes...

**Comment by zelik888** [comment]
Your right. But actually it's because I don't know how to spell password (typed pasword) My mistake!
