### ISSUE TITLE
Fahrenheit

### ISSUE THREAD

**Issue by greedy-dev** [nitaybz/homebridge-tado-ac#60]
When fahrenheit is chosen as unit , not every target temperature number can be set ( I mean I only can set 61,63,64,66,...,75,77,79,81,82,etc. )
I think it’s because plugin sets the temperature with celsius via formula ( (f-32)/1.8 ) and rounds number.
The actual room temperature is displayed correctly , though.
Please fix it cause it’s really frustrating.

**Comment by nitaybz** [comment]
I'll fix it... give me a few days

**Comment by greedy-dev** [comment]
So have you fixed it yet?

**Comment by nitaybz** [comment]
sorry man... couldn't find the time... will let you know here when it's fixed

**Comment by nitaybz** [comment]
Hey!
I know it's been a long time.... but if you're still experiencing these issues and need my help I'm free to help now..

I did a small fix to the latest version (3.2) so it will round to floor instead of just round it... so this could solve the issue.
However, if the issue persist, in order to fix your problem I'll need your help... please add `”debug”: true` to your config and change temperatures on Home app, look in the logs for the text `Got temp command:` and let me know what is the value you see compared to the value you entered in Home app... I'll try to fix it as quickly as possible.

thanks for the long wait

**Comment by greedy-dev** [comment]
The problem still remains, there are just two points on scale for each temperature number (the temperature goes like 73, 73, 75, 75, 77, 79, 79, ..., screen recording: https://share.icloud.com/photos/0uiZgSP2tqi1JBM2xgYIoGbsw ), when I set to 81, the AC sets to 80 (log on the screenshot, I couldn’t copy it on iPad)
![IMG_8459](https://user-images.githubusercontent.com/33165369/66519972-f2ea4200-eaf0-11e9-8096-31082ef01b68.jpeg)
I think the problem is that your plugin sets the temperature in Celsius even when tado has Fahrenheit set as unit (it has native °F support). 1°C ≈ 2°F so that’s why there’s 2°F step.

Maybe there’s a way to parse temperature data and send target temperature directly in °F without conversion (detect the unit that has been set in tado app) (_I’m not a programmer, just my thoughts about the problem_)

**Comment by nitaybz** [comment]
the real problem actually is not the plugin but HomeKit itself... it only acts with Celsius, even when you control it on your side with Fahrenheit, it sends data in Celsius, then I try to convert it into Fahrenheit for Tado app and for logs purposes.

in your logs you can see:
"Got temp command: 28"
"Got temp command: 27"

28 and 27 are the values i'm getting directly from your selection... and they are rounded so it changes the number...
maybe you have anywhere to change that settings to be native Fahrenheit.

I'll keep digging

**Comment by greedy-dev** [comment]
I can change the target temperature in °F in Tado app or on my.tado.com natively. So maybe there’s a way to set the target temperature/get current temperature without any conversions

**Comment by nitaybz** [comment]
Tado app is not our problem... they can accept both parameter easily...
My issue is that you choose some value in Fahrenheit in the Home app and I get that value converted to Celsius

**Comment by nitaybz** [comment]
I tried to implement a fix  I saw online...
can you try and install the branch "f_fix" from github?

it may solve it, or at least try to pull the logs like you did before.

**Comment by greedy-dev** [comment]
Sorry for long response time, had my Raspberry Pi broken and didn't have time to buy a new one.

The issue is still there.

> [12/12/2019, 3:52:14 AM] [Tado AC] Updating Accessory for Bedroom Tado
> [12/12/2019, 3:52:14 AM] [Tado AC] Bedroom Tado *New State* - Mode - COOL
> [12/12/2019, 3:52:14 AM] [Tado AC] Bedroom Tado *New State* - Swing - ON
> [12/12/2019, 3:52:14 AM] [Tado AC] Bedroom Tado *New State* - Fan Speed - LOW
> [12/12/2019, 3:52:14 AM] [Tado AC] Bedroom Tado *New State* - Cooling Threshold Temperature - 61 ºF
> [12/12/2019, 3:52:16 AM] [Tado AC] Bedroom -> Setting Cooling Threshold Temperature: temp 17
> [12/12/2019, 3:52:17 AM] [Tado AC] Got coolTemp command:  17
> [12/12/2019, 3:52:17 AM] [Tado AC] Setting new state on Bedroom -->
> [12/12/2019, 3:52:17 AM] [Tado AC] { termination: { type: 'MANUAL' },
>   setting:
>    { power: 'ON',
>      type: 'AIR_CONDITIONING',
>      mode: 'COOL',
>      temperature: { fahrenheit: 62, celsius: 17 },
>      fanSpeed: 'LOW',
>      swing: 'ON' } }
> setOverlay response: { type: 'MANUAL',
>   setting:
>    { type: 'AIR_CONDITIONING',
>      power: 'ON',
>      mode: 'COOL',
>      temperature: { celsius: 16.67, fahrenheit: 62 },
>      fanSpeed: 'LOW',
>      swing: 'ON' },
>   termination:
>    { type: 'MANUAL',
>      typeSkillBasedApp: 'MANUAL',
>      projectedExpiry: null } }

The temperature threshold is set in celsius (I have ºF set in home app and in Tado app). The plugin still gets commands in ºC, so to resolve this, I think, the problem is that plugin gets characteristics and sets the threshold in ºC, ignoring temperatureUnit so the scale ≈2.

**Comment by nitaybz** [comment]
Should be fixed on version 4 !

Hope someone can approve that it works as expected

**Comment by greedy-dev** [comment]
Now it seems to be working fine. Thanks for fixing. I’ll let you know if there are any other issues.

**Comment by nitaybz** [comment]
Thanks for the quick feedback
