### ISSUE TITLE
Process crash on setting temperature

### ISSUE THREAD

**Issue by ghost** [nitaybz/homebridge-tado-ac#61]
I've been changing the temperature successfully all day until this evening when I changed it, the process on my Mac crashed.

> [1/6/2019, 8:55:42 PM] Homebridge is running on port 51826.
> [1/6/2019, 8:55:44 PM] [TadoAC] Home Current Temperature is 24.56ºC
> [1/6/2019, 8:55:44 PM] [TadoAC] Home Current Mode is  AUTO
> /usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:521
>                             this.lastOverlay[overlayMode].setting.temperature.fahrenheit = Math.round(commands['temp'] * 9 / 5 + 32)
>                                                                                          ^
> 
> TypeError: Cannot set property 'fahrenheit' of undefined
>     at Timeout.setTimeout (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:521:90)
>     at ontimeout (timers.js:380:14)
>     at tryOnTimeout (timers.js:244:5)
>     at Timer.listOnTimeout (timers.js:214:5)

This kept happening after every time I restarted the process. I'm running on macOS 10.14.2.

**Comment by nitaybz** [comment]
is it still happening?
what version of the plugin are you running?

**Comment by nitaybz** [comment]
If the issue persist let me know, if not I'll close the issue
