### ISSUE TITLE
Request: Thermostat sensor?

### ISSUE THREAD

**Issue by ghost** [nitaybz/homebridge-tado-ac#62]
Hi there.

This isn't as much of an issue as a feature request. I was wondering if it's possible to use the device as a thermostat sensor through HomeKit? This would let you set up an automation in the Home app for when the temperature reaches a certain value, etc.

P.S. Great work so far on getting this working!

**Comment by nitaybz** [comment]
This can be achieved with HomeKit 3rd party apps like "Eve" or "Hesperus"

just set it to:
IF (trigger) "Temperature Sensor Changed to anything"
IF (condition) "Temperature is bigger than (some value)"
THEN, "Activate COOL mode on AC"


It's not gonna be done from within the plugin as there are many other options to achieve that
