### ISSUE TITLE
Tado not responding to orders

### ISSUE THREAD

**Issue by rafacampoamor** [nitaybz/homebridge-tado-ac#64]
I've installed v3 after months of home bridge problems and finally got it working. Problem is home app show what Todo is doing but doesn't send the orders to Tado API. My Todo y on Thermostatic control, and if I have it on "off" position and try to set it to 23 degrees, homebridge shows the following:

`[2019-1-27 23:42:26] [Tado AC] Setting Salón AC to HEAT`
`[2019-1-27 23:42:38] [Tado AC] Setting Salón AC Target Temperature to 24
`

But nothing happens on the Tado app until Home app shows it as off again

`[2019-1-27 23:42:26] [Tado AC] Setting Salón AC to HEAT`
`[2019-1-27 23:42:38] [Tado AC] Setting Salón AC Target Temperature to 24`
`[2019-1-27 23:50:41] [Tado AC] Someone is Home!`
`[2019-1-27 23:50:42] [Tado AC] Salón Current Temperature is 22.23ºC`
`[2019-1-27 23:50:42] [Tado AC] Salón Mode is OFF`
`

**Comment by nitaybz** [comment]
I think you don't have the latest version... as we talked in the other issue...
