### ISSUE TITLE
Request for "Dry" mode

### ISSUE THREAD

**Issue by sithipong** [nitaybz/homebridge-tado-ac#68]
Would it be possible to add "Dry" mode? The latest homebridge-tado-ac no longer crashes Homebridge when I turn on Dry mode via the Tado app. However the AC would instead show up as "Off" in the Home app, it would be nice if we can also enable "Dry" via the Home app itself.

**Comment by nitaybz** [comment]
I'll create it in a future version... not so soon i'm afraid...

**Comment by sithipong** [comment]
Thanks for the quick reply, looking forward to it, and thank you for the awesome plugin!

**Comment by nitaybz** [comment]
added in the latest version 4 !
