### ISSUE TITLE
autoFanonly

### ISSUE THREAD

**Issue by philmue1988** [nitaybz/homebridge-tado-ac#69]
Dear guys,

i tried to install and discover that when "autoFanOnly": is set to "true" the Homebridge will start normally but when i tried to set to "false" homebrigde is crashing with the follwing notes :

TypeError: Cannot read property 'fanSpeeds' of undefined
Mar 12 01:05:25 raspberrypi homebridge[1018]:     at getMaxSpeed (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:549:44)
Mar 12 01:05:25 raspberrypi homebridge[1018]:     at TadoAccessory.getServices (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:556:52)
Mar 12 01:05:25 raspberrypi homebridge[1018]:     at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:410:36)
Mar 12 01:05:25 raspberrypi homebridge[1018]:     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:396:32)
Mar 12 01:05:25 raspberrypi homebridge[1018]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
Mar 12 01:05:25 raspberrypi homebridge[1018]:     at async.waterfall (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:308:17)
Mar 12 01:05:25 raspberrypi homebridge[1018]:     at /usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:473:16
Mar 12 01:05:25 raspberrypi homebridge[1018]:     at next (/usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:5329:29)
Mar 12 01:05:25 raspberrypi homebridge[1018]:     at /usr/local/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:969:16

was there something wrong from my side or is there a fix problem with that

**Comment by philmue1988** [comment]
for using the low/medium and high fan speed

**Comment by nitaybz** [comment]
please show me your config...
also can you tell me which plugin version are you using?

**Comment by philmue1988** [comment]
hi thank you for the quick reply! 
i installed newest version via sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac.git
my config is:
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:DC:02:C1:F2:5A",
        "port": 51826,
        "pin": "597-15-139"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "red",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            }
        },
        {
            "platform": "TadoAC",
            "name": "Klimaanlage",
            "username": "XXXX@gmail.com",
            "password": "XXX",
            "homeID": 316XXX,
            "weatherSensorsEnabled": false,
            "weatherPollingInterval": 10,
            "occupancySensorsEnabled": false,
            "occupancyPollingInterval": 10,
            "anyoneSensor": false,
            "tadoMode": "MANUAL",
            "durationInMinutes": 100,
            "autoFanOnly": true,
            "manualControlSwitch": true,
            "disableHumiditySensor": false,
            "extraHumiditySensor": [
                "Living Room",
                3
            ],
            "disableFan": false
        }
    ],
    "accessories": []
}

**Comment by nitaybz** [comment]
Please try to install again

**Comment by philmue1988** [comment]
yes now it´s working! thank you!

**Comment by nitaybz** [comment]
I'm glad!
no problem

**Comment by philmue1988** [comment]
Hi nitaybz,

unfortunately i had to reinstall my bridge now when i run the command the following message shows up:

do you have an idea?

pi@raspberrypi:~ $ sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac.git
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/nitaybz/homebridge-tado-ac.git /root/.npm/_cacache/tmp/git-clone-37810c0d/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-37810c0d/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-02T07_53_47_609Z-debug.log

Phil
