### ISSUE TITLE
Adjusting Temp via Siri results in AC turning off

### ISSUE THREAD

**Issue by L3x1c0n** [nitaybz/homebridge-tado-ac#7]
I'm not sure what's the issue because its not always the case, but more often than not when I ask Siri to adjust the temperature up or down the AC just powers down.

**Comment by nitaybz** [comment]
Do you have the latest version installed?
Can you provide logs?

**Comment by nitaybz** [comment]
@L3x1c0n can I close the issue? is it solved?
