### ISSUE TITLE
start then crash

### ISSUE THREAD

**Issue by sklu81** [nitaybz/homebridge-tado-ac#75]
First of all many thanks for your work! 
Unfortunately I run into a problem with my homebridge on a raspi and homebridge doesn't start anymore. Config is the simple one: Just Username and Password. Here is the log: 

Apr 19 14:47:27 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Apr 19 14:47:28 raspberrypi homebridge[16263]: [4/19/2019, 2:47:28 PM] Loaded config.json with 1 accessories and 2 platforms.
Apr 19 14:47:28 raspberrypi homebridge[16263]: [4/19/2019, 2:47:28 PM] ---
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] Loaded plugin: homebridge-airrohr
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] Registering accessory 'homebridge-airrohr.airrohr'
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] ---
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] Loaded plugin: homebridge-config-ui-x
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] Registering platform 'homebridge-config-ui-x.config'
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] ---
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] Loaded plugin: homebridge-tado-ac
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] Registering platform 'homebridge-tado-ac.TadoAC'
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] ---
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] Loading 2 platforms...
Apr 19 14:47:29 raspberrypi homebridge[16263]: [4/19/2019, 2:47:29 PM] [Config] Initializing config platform...
Apr 19 14:47:30 raspberrypi homebridge[16263]: [4/19/2019, 2:47:30 PM] [Config] Spawning homebridge-config-ui-x with PID 16286
Apr 19 14:47:30 raspberrypi homebridge[16263]: [4/19/2019, 2:47:30 PM] [TadoAC] Initializing TadoAC platform...
Apr 19 14:47:30 raspberrypi homebridge[16263]: [4/19/2019, 2:47:30 PM] Loading 1 accessories...
Apr 19 14:47:30 raspberrypi homebridge[16263]: [4/19/2019, 2:47:30 PM] [AirRohr] Initializing airrohr accessory...
Apr 19 14:47:30 raspberrypi homebridge[16263]: [4/19/2019, 2:47:30 PM] [AirRohr] AirRohr: Update interval 60 s
Apr 19 14:47:30 raspberrypi homebridge[16263]: [4/19/2019, 2:47:30 PM] TypeError: zones.filter is not a function
Apr 19 14:47:30 raspberrypi homebridge[16263]:     at tadoApi.getZones (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:119:39)
Apr 19 14:47:30 raspberrypi homebridge[16263]:     at IncomingMessage.res.on (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:118:17)
Apr 19 14:47:30 raspberrypi homebridge[16263]:     at IncomingMessage.emit (events.js:198:15)
Apr 19 14:47:30 raspberrypi homebridge[16263]:     at endReadableNT (_stream_readable.js:1139:12)
Apr 19 14:47:30 raspberrypi homebridge[16263]:     at processTicksAndRejections (internal/process/task_queues.js:81:17)
Apr 19 14:47:30 raspberrypi homebridge[16263]: [4/19/2019, 2:47:30 PM] Got SIGTERM, shutting down Homebridge...
Apr 19 14:47:34 raspberrypi homebridge[16263]: [4/19/2019, 2:47:34 PM] [homebridge-config-ui-x] Console v4.0.1 is listening on port 8080
Apr 19 14:47:35 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Apr 19 14:47:35 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Apr 19 14:47:35 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by nitaybz** [comment]
you need to update your node version

**Comment by sebastian325** [comment]
Same problem here,node version should be the newest doesnt help

@sklu81 could you solve the problem?

**Comment by nitaybz** [comment]
Did you install homebridge again after updating node?

**Comment by sebastian325** [comment]
Yes, I did so
Do you mean after the crash or before?

**Comment by sebastian325** [comment]
here are the config.json and Logfile

config.json


{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:31",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "red",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "sudo": true,
            "log": {
                "method": "custom",
                "command": "journalctl -o cat -n 500 -f -u homebridge"
            }
        }
    ],
    "accessories": [
        {
            "platform": "TadoAC",
            "username": „xxx@xxx.xxx",
            "password": „xxxxxx“
        }
    ]
}


Logfile

Jun 28 19:56:03 raspberrypi systemd[1]: homebridge.service: Service RestartSec=10s expired, scheduling restart.
Jun 28 19:56:03 raspberrypi systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 1.
Jun 28 19:56:03 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Jun 28 19:56:03 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] Loaded config.json with 1 accessories and 1 platforms.
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] ---
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] Loaded plugin: homebridge-config-ui-x
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] Registering platform 'homebridge-config-ui-x.config'
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] ---
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] Loaded plugin: homebridge-tado-ac
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] Registering platform 'homebridge-tado-ac.TadoAC'
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] ---
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] Loading 1 platforms...
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] [Config] Initializing config platform...
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] [Config] Spawning homebridge-config-ui-x with PID 27246
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] Loading 1 accessories...
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] TypeError: Cannot read property 'indexOf' of undefined
Jun 28 19:56:05 raspberrypi homebridge[27226]:     at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:12)
Jun 28 19:56:05 raspberrypi homebridge[27226]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
Jun 28 19:56:05 raspberrypi homebridge[27226]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Jun 28 19:56:05 raspberrypi homebridge[27226]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Jun 28 19:56:05 raspberrypi homebridge[27226]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jun 28 19:56:05 raspberrypi homebridge[27226]:     at Module._compile (internal/modules/cjs/loader.js:776:30)
Jun 28 19:56:05 raspberrypi homebridge[27226]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
Jun 28 19:56:05 raspberrypi homebridge[27226]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Jun 28 19:56:05 raspberrypi homebridge[27226]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Jun 28 19:56:05 raspberrypi homebridge[27226]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Jun 28 19:56:05 raspberrypi homebridge[27226]: [6/28/2019, 7:56:05 PM] Got SIGTERM, shutting down Homebridge...
Jun 28 19:56:09 raspberrypi homebridge[27226]: [6/28/2019, 7:56:09 PM] [Config] Console v4.5.1 is listening on :: port 8080
Jun 28 19:56:10 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Jun 28 19:56:10 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by nitaybz** [comment]
The error is because you put Tado as an accessory while you should use it as a platform... this is a different issue than described earlier

**Comment by sebastian325** [comment]
Ok, I will try it!

**Comment by nitaybz** [comment]
Works?

**Comment by sebastian325** [comment]
Yes it does, thanks a lot
