### ISSUE TITLE
Expose other sensors but not thermostat?

### ISSUE THREAD

**Issue by ifeign** [nitaybz/homebridge-tado-ac#79]
I was wondering if there were a way to hide the thermostat? I'm happy with the native Homekit accessory, I was just hoping to expose the other sensors - humidity, occupancy etc.

**Comment by nitaybz** [comment]
It's a feature I would have to create... let's leave it open for now and I'll see what I can do.

**Comment by ifeign** [comment]
Thank you

**Comment by nitaybz** [comment]
which sensors would you want to keep? inside temperature and humidity are necessary?

**Comment by ifeign** [comment]
I’m beginning to think this isn’t really necessary. But basically
everything except the thermostat would be nice to have for at-a-glance data.

**Comment by nitaybz** [comment]
ok... I'll see if I can get it to the next update

**Comment by nitaybz** [comment]
In the latest version you can set `"disableAcAccessory": true` and it will remove Tado Main accessory... all other accessories (accept room temp) should be available via parameters in config

**Comment by ifeign** [comment]
Thank you!
