### ISSUE TITLE
How to swith to non-thermostatic mode?

### ISSUE THREAD

**Issue by mensa84** [nitaybz/homebridge-tado-ac#80]
Hello,

I switched my tado to non-thermostatic mode but the homebridge-tado-ac plugin does not recognize that change.
How can I tell the plugin to create heatercooler (AC) accessory instead of thermostatic in HomeKit?

**Comment by nitaybz** [comment]
Try to remove the related files in the persist folder and homebridge will relearn the device

**Comment by nitaybz** [comment]
There might be an issue with Tado API, seen it before, where it is not updating the installation mode properly... you can force it now by installing the plugin's latest version (3.2) and adding `"forceHeaterCooler": true` to your config

**Comment by nitaybz** [comment]
closing...
