### ISSUE TITLE
Fan speed?

### ISSUE THREAD

**Issue by zelik888** [nitaybz/homebridge-tado-ac#87]
I can't figure out how to set the fan speed from homebridge/homekit for my AC units. I can set temperature, mode and i have a separate accessory that is a FAN but that is only on and off and sets the AC to fan (not cool/heat/dry/auto). Is there something I'm not doing correctly? I'm using the latest homebridge-tado-ac and brand new homebridge install. AC unit is a mitsubishi unit, correctly set up in Tado in non-thermostatic mode.

**Comment by nitaybz** [comment]
do you have the possibility to control fan speed from Tado app? if so, you should be able to find it inside the accessory in Home App as part of it's settings.
