### ISSUE TITLE
Back to auto mode? 

### ISSUE THREAD

**Issue by rafacampoamor** [nitaybz/homebridge-tado-ac#88]
Is there an option to get Tado back to “Auto” mode from HomeKit? I have my Tado in non thermostatic mode and use to adjust it according to the situation and miss a “auto” bottom or Siri command to get it back to auto… 

Thanks for all the good work!! 😊

**Comment by nitaybz** [comment]
If you can set Auto through tado app you should be able to do it in Home app as well
