### ISSUE TITLE
Home overriding Tado smart schedule?

### ISSUE THREAD

**Issue by mikesay98** [nitaybz/homebridge-tado-ac#91]
Sorry if this has been discussed before, but I'm pretty new to this. I've set everything up but when I tap on a Tado device in the Home app, even if I don't change a thing, it automatically sets my Tado to that temp until the next smart schedule change. Is there a way to fix this that I'm missing? Thanks!

**Comment by nitaybz** [comment]
what is your expected behaviour? you want your change to be permanent?
if so, set in your config:
`"tadoMode": "MANUAL"`
