### ISSUE TITLE
Device status always on "updating", multiple bugs

### ISSUE THREAD

**Issue by matthieulrg** [nitaybz/homebridge-tado-ac#94]
Hi, I've just reinstalled my homebridge setup and added Tado AC.

I'm having strange issues, here's a video : [https://share.icloud.com/photos/0V4tTx2xfHmvkfQBmtf4oV4ZQ](https://share.icloud.com/photos/0V4tTx2xfHmvkfQBmtf4oV4ZQ)

Description : 
- Each devices constantly says "updating"
- When trying to set a command I have a blank screen

No issues with my configuration in logs, here's an except : 
[6/5/2020, 17:00:00] [TadoAC] Salon Current Mode is  OFF
[6/5/2020, 17:00:00] [TadoAC] Salon Current Temperature is 31.17ºC
[6/5/2020, 17:00:00] [TadoAC] Salon Humidity is 49.7%
[6/5/2020, 17:00:00] [TadoAC] Cuisine Current Mode is  OFF
[6/5/2020, 17:00:00] [TadoAC] Cuisine Current Temperature is 21.11ºC
[6/5/2020, 17:00:00] [TadoAC] Cuisine Humidity is 50.8%

Here's the config : 
`        {
            "platform": "TadoAC",
            "username": "xxx",
            "password": "xxx",
            "occupancySensorsEnabled": false,
            "tadoMode": "MANUAL",
            "disableHumiditySensor": false
        },`

**Comment by javierireyes** [comment]
I'm having the same issue, my tado hardware version is v2.

**Comment by nitaybz** [comment]
@mattnsr from your logs it seems like the device is getting the status... how do you know that it is coming from this plugin?
can you share some more logs?

**Comment by matthieulrg** [comment]
Hi @nitaybz I don't have many more logs, no issues appear in the logs... It's my only plugin on homebridge, the install is brand new...

Maybe @javierireyes has more logs? I'm using tado v1

**Comment by javierireyes** [comment]
Hi, I've just checked my logs and there are no error on behalf of the Tado Plug-In, actually it appears to be working just fine:

[6/30/2020, 9:23:37 AM] [TadoAC] Cuarto de Kiki Current Mode is  OFF
[6/30/2020, 9:23:37 AM] [TadoAC] Cuarto de Kiki Current Temperature is 77.67ºF

but on Homekit:

![IMG_A910D52984E8-1](https://user-images.githubusercontent.com/57547171/86132248-a7c7f300-bab4-11ea-8196-8dca3a0f541b.jpeg)

**Comment by nitaybz** [comment]
try adding "debug": true to your config and let's see if we see anything useful

**Comment by javierireyes** [comment]
Here's the log after the homebridge restart:

[homebridge.log](https://github.com/nitaybz/homebridge-tado-ac/files/4852322/homebridge.log)

**Comment by nitaybz** [comment]
thanks, that helps... please try a test:
use Tado app to turn ON device, wait 5 seconds, go back to Home app, see if you can get a status.
post me all the logs of this test.
I'll investigate and come back with a fix.

**Comment by javierireyes** [comment]
Sorry Guys but I've pulled the plug on the Tado AC, I've just received a Sensibo.  If anyone is interested I'll be selling the Tado on eBay.

**Comment by nitaybz** [comment]
Sensibo plugin is also mine ;)

**Comment by matthieulrg** [comment]
Hi @nitaybz I tried this and got those logs:

> [7/12/2020, 17:33:04] [Homebridge BB-8] Starting terminal session
> [7/12/2020, 17:33:09] [TadoAC] Salon Current Mode is  OFF
> [7/12/2020, 17:33:09] [TadoAC] Salon Current Temperature is 26.03ºC
> [7/12/2020, 17:33:09] [TadoAC] Salon Humidity is 36.5%
> [7/12/2020, 17:33:09] [TadoAC] Cuisine Current Mode is  OFF
> [7/12/2020, 17:33:09] [TadoAC] Cuisine Current Temperature is 23.48ºC
> [7/12/2020, 17:33:09] [TadoAC] Cuisine Humidity is 40.3%
> [7/12/2020, 17:33:14] [TadoAC] Chambre Mode is  OFF
> [7/12/2020, 17:33:14] [TadoAC] Chambre Current Temperature is 23.88ºC
> [7/12/2020, 17:33:14] [TadoAC] Chambre Humidity is 39.6%
> [7/12/2020, 17:33:14] [TadoAC] Chambre Mode is  OFF
> [7/12/2020, 17:33:14] [TadoAC] Chambre Current Temperature is 23.88ºC
> [7/12/2020, 17:33:14] [TadoAC] Chambre Humidity is 39.6%
> [7/12/2020, 17:33:14] [TadoAC] Salon Current Mode is  OFF
> [7/12/2020, 17:33:14] [TadoAC] Salon Current Temperature is 26.03ºC
> [7/12/2020, 17:33:14] [TadoAC] Salon Humidity is 36.5%
> [7/12/2020, 17:33:19] [TadoAC] Cuisine Current Mode is  OFF
> [7/12/2020, 17:33:19] [TadoAC] Cuisine Current Temperature is 23.48ºC
> [7/12/2020, 17:33:19] [TadoAC] Cuisine Humidity is 40.3%
> [7/12/2020, 17:34:15] [TadoAC] Cuisine Current Temperature is 23.48ºC
> [7/12/2020, 17:34:15] [TadoAC] Cuisine Current Mode is  OFF
> [7/12/2020, 17:34:20] [TadoAC] Salon Target Temperature is 21ºC
> [7/12/2020, 17:34:20] [TadoAC] Salon Current Mode is  COOL
> [7/12/2020, 17:34:20] [TadoAC] Salon Current Temperature is 26.03ºC
> [7/12/2020, 17:34:35] [TadoAC] Chambre Mode is  OFF
> [7/12/2020, 17:34:35] [TadoAC] Chambre Current Temperature is 23.86ºC
> [7/12/2020, 17:34:40] [TadoAC] Salon Current Mode is  OFF
> [7/12/2020, 17:34:40] [TadoAC] Salon Current Temperature is 26.03ºC
> [7/12/2020, 17:34:40] [TadoAC] Cuisine Current Temperature is 23.48ºC
> [7/12/2020, 17:34:40] [TadoAC] Cuisine Current Mode is  OFF

<img width="332" alt="MacBook Pro screenshot 2020-07-12 at 18 34 25" src="https://user-images.githubusercontent.com/29901673/87251777-8250c700-c46e-11ea-9743-75261334d5f6.png">

**Comment by nitaybz** [comment]
Are you running thermostatic more on tado app or in the plugin config?

**Comment by matthieulrg** [comment]
No, I’m in non thermostatic mode

**Comment by matthieulrg** [comment]
Hi @nitaybz any updates? :)

**Comment by nitaybz** [comment]
Hey!
I'm doing a complete refactoring for the entire plugin, it will be smart and more efficient and will also include some cool new features... please be a bit more patient and it will worth it

**Comment by matthieulrg** [comment]
So cool, thanks !

**Comment by nitaybz** [comment]
@mattnsr it took some time but as promised... completely new code, should solve most of the plugin's previous issues...
let me know if it all worked out.

Try version 4
