### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by mikesay98** [nitaybz/homebridge-tado-ac#96]
My Hoobs has been shutting down randomly. I sent the log info to them and they said the Tado Plugin is "reporting invalid credentials according to the logs."

<img width="1705" alt="Screen Shot 2020-08-11 at 10 47 19 AM" src="https://user-images.githubusercontent.com/45052222/89936829-15ddfa80-dbc9-11ea-8728-f57d35769cf4.png">

**Comment by nitaybz** [comment]
is the issue still persist?

try to install version 4 and report back please.

**Comment by nitaybz** [comment]
on version 4 the plugin was completely refactored, therefore the problem will not occur on this version.
If other problems occur on version 4, please open a new ticket.
closing...
