### ISSUE TITLE
Temperature keeps reverting to 25 degrees

### ISSUE THREAD

**Issue by ghost** [nitaybz/homebridge-tado-ac#99]
When I ask Siri to "turn on the heater" or "turn on the A/C", the temperature is set to 25 degrees celsius.

I have never set this temperate and never do. It's usually around 22.

![IMG_4748](https://user-images.githubusercontent.com/5070045/97656298-4001d300-1abb-11eb-8263-a835ebd0128c.png)

**Comment by nitaybz** [comment]
Does it happens every time you turn ON he AC? Does it happens with all modes?

**Comment by ghost** [comment]
It happens for heat and cool. I notice sometimes it goes to 18 degrees celsius. I assume that is the minimum and 25 is the maximum. I only have one model, the Smart AC Control.

**Comment by nitaybz** [comment]
Try changing the temperature and see if next time you turn on in the same mode it will turn it on with the same temperature you've set before

**Comment by ghost** [comment]
Unfortunately it seems to reproduce every time for me. Ignores prior settings.

**Comment by nitaybz** [comment]
Please try 4.0.11

**Comment by nitaybz** [comment]
hey @rickydamelio , any news?

**Comment by rickydameliocroc** [comment]
@nitaybz Unfortunately it didn't work.

Ran `$ npm update homebridge-tado-ac`, rebooted the device, and the issue remains. Is there some sort of log I can share with you?

**Comment by nitaybz** [comment]
Please run `npm install -g homebridge-tado-ac` And let me know what version is installed, then, test again if the issue exists

**Comment by ghost** [comment]
Reinstalled to latest. Still going to 18 or 25 degrees for air con and heater, respectively.

**Comment by ghost** [comment]
Actually it seems to be working now, maybe it's fixed.

**Comment by nitaybz** [comment]
Glad it worked :)
